static/CNAME
ref: https://gohugo.io/hosting-and-deployment/hosting-on-github/#use-a-custom-domain
=> chore: add custom-domain

config.toml
fixed https://github.com/cloudwego/cloudwego.github.io/issues/42
=> fix(sidebar): update github_repo to fix links in sidebar

content/en/_index.html
=> refactor: netpol->netpoll

.github/workflows/gh-pages.yml
=> chore: production env

content/en/about/_index.html
=> update about page

content/en/_index.html
Add one whitespace between `.` and new sentence.
=> [doc] Add one whitespace between `.` and new sentence

assets/scss/home.scss, content/en/_index.html, content/zh/_index.html
=> feat: section of cncf-landscape

assets/scss/home.scss
=> fix: update flex-width for mobile

content/zh/blog/news/bytedance_gonet_practice/index.md
=> Modification

content/en/blog/news/kitex-perf-optimize-practices/index.md
add translated english blog post "performance optimization on kitex"
=> add english blog post

content/zh/blog/news/kitex-perf-optimize-practices/index.md
=> blog layout modification

content/en/blog/releases/Kitex/release-v008.md, content/zh/blog/releases/Kitex/release-v008.md
=> add release note

content/en/about/_index.html, content/zh/about/_index.html
=> mainpage about modification

content/en/blog/news/kitex_performance_testing/index.md, content/zh/blog/news/Kitex_performance_testing/index.md
=> add_new_eng_blog

content/en/blog/news/bytedance_gonet_practice/index.md, content/en/blog/news/kitex-perf-optimize-practices/index.md, content/en/blog/news/kitex_performance_testing/index.md, content/zh/blog/news/Kitex_performance_testing/index.md, content/zh/blog/news/bytedance_gonet_practice/index.md, content/zh/blog/news/kitex-perf-optimize-practices/index.md
modify blog posts authors to github links
=> modify_blog_author

layouts/partials/navbar.html, layouts/partials/sidebar-tree.html
set document as a folder，sub-doc-menu supported
=> feat(layout): sub-menu & doc-folder supported

layouts/404.html
`alias` is for post-file
mock alias for posts-folder
=> chore: mock-alias for 404

layouts/404.html
ref: https://github.com/cloudwego/cloudwego.github.io/pull/118
fix 404-alias for multiLingual
=> fix(404): redirect-alias for i18n

content/en/blog/releases/Kitex/release-v010.md, content/zh/blog/releases/Kitex/release-v008.md, content/zh/blog/releases/Kitex/release-v010.md
add zh/en kitex v010 release notes
=> doc: add_release_notes

content/zh/docs/netpoll/_index.md
=> modify_netpoll_docs

content/en/_index.html, content/en/docs/netpoll/Caution/_index.md, content/en/docs/netpoll/Common Usage/_index.md, content/en/docs/netpoll/Getting started/_index.md, content/zh/_index.html, content/zh/docs/netpoll/Caution/_index.md, content/zh/docs/netpoll/Common Usage/_index.md, content/zh/docs/netpoll/Getting started/_index.md
- split original netpoll docs into three docs
- add netpoll to the homepage footer
=> chore: split netpoll docs

content/en/blog/releases/Netpoll/release-v010.md, content/en/blog/releases/Netpoll/release-v011.md, content/en/blog/releases/Netpoll/release-v012.md
=> add_netpoll_release_note

content/en/blog/releases/Kitex/release-v014.md, content/zh/blog/releases/Kitex/release-v013.md, content/zh/blog/releases/Kitex/release-v014.md
ref: https://github.com/cloudwego/kitex/releases/tag/v0.1.4
=> chore: add kitex v0.1.4 release notes

content/en/blog/news/kitex_performance_testing/index.md, content/zh/blog/news/Kitex_performance_testing/index.md
Ref: [RPC 框架 Kitex 实践入门：性能测试指南](https://www.cloudwego.io/zh/blog/2021/11/24/rpc-%E6%A1%86%E6%9E%B6-kitex-%E5%AE%9E%E8%B7%B5%E5%85%A5%E9%97%A8%E6%80%A7%E8%83%BD%E6%B5%8B%E8%AF%95%E6%8C%87%E5%8D%97/)
changes:
1. fix one paragraph wrong layout
2. add intro for [The Characteristics of Microservice Scenario]
3. fix typos
4. adjust some wrong or improper words with better ones
5. add blank Lines for paragraphs
=> chore: update kitex blog [2021-11-24]

content/en/blog/news/kitex_performance_testing/index.md, content/en/blog/releases/Kitex/release-v020.md, content/en/blog/releases/Netpoll/release-v020.md, content/zh/blog/releases/Kitex/release-v020.md, content/zh/blog/releases/Netpoll/release-v020.md
add release notes for v0.2.0
ref: 
- https://github.com/cloudwego/kitex/releases/tag/v0.2.0
- https://github.com/cloudwego/netpoll/releases/tag/v0.2.0
=> add release notes for v0.2.0

config.toml, layouts/partials/footer.html
=> refactor: footer-links supported

content/en/docs/kitex/Tutorials/framework-exten/middleware.md, content/zh/docs/kitex/Tutorials/framework-exten/middleware.md
en: update middleware docs
zh: 更正了middleware的说明文档
=> docs: update middlewares docs

content/zh/docs/hertz/tutorials/basic-feature/middleware/basic-auth.md
=> fix: fix the bug that basic-auth.md doesn't work

content/en/docs/kitex/Tutorials/options/_index.md, content/en/docs/kitex/Tutorials/options/call_options.md, content/en/docs/kitex/Tutorials/options/client_options.md, content/en/docs/kitex/Tutorials/options/server_options.md, content/zh/docs/kitex/Tutorials/options/_index.md, content/zh/docs/kitex/Tutorials/options/call_options.md, content/zh/docs/kitex/Tutorials/options/client_options.md, content/zh/docs/kitex/Tutorials/options/server_options.md
en: add options
zh: 添加了option的说明文档
=> docs: add options

content/en/docs/hertz/tutorials/framework-exten/_index.md, content/en/docs/hertz/tutorials/framework-exten/monitor.md
translate hertz/tutorials/tutorials/framework-exten/monitor
[https://github.com/cloudwego/hertz/issues/81](https://github.com/cloudwego/hertz/issues/81
)
=> [docs]: translate hertz/tutorials/tutorials/framework-exten/monitoring #81

content/en/docs/hertz/tutorials/framework-exten/log.md, content/en/docs/kitex/Tutorials/basic-feature/logging.md
translate hertz/tutorials/tutorials/framework-exten/log
[https://github.com/cloudwego/hertz/issues/81](https://github.com/cloudwego/hertz/issues/81)
=> [docs]: translate hertz/tutorials/tutorials/framework-exten/log

content/en/docs/hertz/tutorials/basic-feature/network-lib.md
docs: translate hertz/tutorials/basic-feature/network-lib
=> docs: translate hertz/tutorials/basic-feature/network-lib

content/en/docs/hertz/tutorials/service-governance/_index.md, content/en/docs/hertz/tutorials/service-governance/monitoring.md, content/en/docs/hertz/tutorials/service-governance/tracing.md, content/zh/docs/hertz/tutorials/service-governance/monitoring.md
translate hertz tutorials/tutorials/service-governance/monitoring/ [#79](https://github.com/cloudwego/hertz/issues/79)
=> [docs]: translate hertz tutorials/tutorials/service-governance/monitoring/ #79

content/en/docs/kitex/Tutorials/advanced-feature/grpcproxy.md, content/zh/docs/kitex/Tutorials/advanced-feature/grpcproxy.md
en: add docs for grpc proxy example
zh: 添加了 grpc proxy 使用示范的文档
=> docs: update grpc proxy example docs

content/en/docs/hertz/getting-started/_index.md
docs: Update the translation of hertz Getting Started
=> docs: Update the translation of hertz Getting Started

content/en/docs/hertz/reference/_index.md, content/en/docs/hertz/reference/config.md
docs: translate reference config
=> docs: translate reference config

content/en/docs/hertz/tutorials/basic-feature/forward-proxy.md, content/en/docs/hertz/tutorials/basic-feature/graceful-shutdown.md, content/en/docs/hertz/tutorials/basic-feature/unit-test.md, content/zh/docs/hertz/tutorials/basic-feature/unit-test.md
Related issue: https://github.com/cloudwego/hertz/issues/72
=> [docs]:translate hertz/tutorials/basic-feature/graceful-shutdown, forward-proxy and unit-test

content/en/docs/hertz/tutorials/basic-feature/error-handle.md, content/en/docs/hertz/tutorials/basic-feature/log.md, content/en/docs/hertz/tutorials/basic-feature/protocol.md
docs: Document only changes.
en: translate hertz/tutorials/basic-feature/protocol, log, err handle
zh: 翻译 hertz/tutorials/basic-feature/protocol, log, err handle
https://github.com/cloudwego/hertz/issues/71
=> [docs]: translate hertz/tutorials/basic-feature/protocol, log, err handle

.gitignore, assets/scss/_nav.scss, layouts/partials/navbar.html
feat: mobile friendly navbar
Sub-navbar disappear on small screen device.
Old version
New version
=> feat: mobile friendly navbar

layouts/partials/navbar.html
fix: language switch button missing on mobile screen
fix: language switch button missing on mobile screen
=> fix: language switch button missing

content/zh/docs/kitex/Tutorials/basic-feature/transport_protocol.md
docs
en: docs: optimize setup description for the transport protocol
zh: docs: 优化传输协议配置描述
none
=> docs: optimize setup description for transport protocol 

content/en/docs/hertz/reference/json.md, content/zh/docs/hertz/reference/json.md
Signed-off-by: 范舒阳 <fanshuyang@bytedance.com>
docs
en: add missing new line in FAQ section
zh: 修复常见问题缺少的空行
=> docs: add missing new line

content/en/_index.html, content/en/about/_index.html, content/zh/_index.html, content/zh/about/_index.html
chore
en:  update CloudWeGo about and description
zh: 更新 CloudWeGo 关于和主页介绍
=> chore: update CloudWeGo about and description

package-lock.json, package.json
Reverts cloudwego/cloudwego.github.io#274
=> Revert "chore(deps-dev): bump postcss-cli from 7.1.2 to 10.0.0"

content/zh/docs/kitex/Tutorials/basic-feature/circuitbreaker.md
=> style(circuitbreaker.md)

content/zh/docs/kitex/Tutorials/framework-exten/registry.md
docs
en: docs: adjust Chinese doc of registry extension 
zh:docs:  调整注册扩展的中文文档
none
=> docs: adjust Chinese doc of registry extension 

content/zh/docs/hertz/getting-started/_index.md
after I execute curl command, the output changes. And the output string is `{"message":"pong"}`, I has fixed the fault.
en: 
zh:
=> fix document bug

content/zh/docs/hertz/tutorials/framework-exten/service_discovery.md, content/zh/docs/hertz/tutorials/service-governance/service_discovery.md
en:  添加服务发现的相关文档
zh: add service discovery's doc
=> feat: add sd doc

content/en/docs/netpoll/Getting started/_index.md, content/zh/docs/netpoll/Getting started/_index.md
fix: spelling error
en: netpoll getting started doc spell error
zh: netpoll快速开始文档拼写错误
=> fix: spelling error

config.toml
feat: enable offline search
en: enable offline search
zh: 启用离线搜索功能
Fixes #302
=> feat: enable offline search

content/zh/docs/volo/volo-grpc/getting-started/part_2.md
fix
en: fix docs error in volo grpc init 
zh: 修复volo grpc init文档的错误
fix https://github.com/cloudwego/volo/issues/12
=> fix: volo grpc init example

content/zh/docs/volo/volo-grpc/getting-started/part_1.md, content/zh/docs/volo/volo-grpc/getting-started/part_2.md, content/zh/docs/volo/volo-grpc/getting-started/part_3.md, content/zh/docs/volo/volo-grpc/getting-started/part_4.md, content/zh/docs/volo/volo-thrift/getting-started/part_1.md, content/zh/docs/volo/volo-thrift/getting-started/part_2.md, content/zh/docs/volo/volo-thrift/getting-started/part_4.md
en: fix error in volo example documents
zh: 修复volo示例文档中的错误
=> fix: volo getting-started doc

content/zh/docs/volo/guide/discovery_lb.md, content/zh/docs/volo/guide/metadata.md, content/zh/docs/volo/guide/observability.md, content/zh/docs/volo/guide/with_callopt.md
fix
en: fix volo guide documents error
zh: 修复volo guild文档中的错误
=> fix: volo guide doc

content/en/docs/kitex/Tutorials/advanced-feature/xds.md, content/zh/docs/kitex/Tutorials/advanced-feature/xds.md
doc
en: doc: add doc for xDS Support, including introduction and usage .
zh: doc: 为 xDS 支持添加说明文档，包括介绍及用法
=> doc: add doc for xds

content/en/docs/kitex/Tutorials/code-gen/fastpb.md, content/zh/docs/kitex/Tutorials/code-gen/fastpb.md
docs
en: add fastpb plugin description
zh: 补充 fastpb 相关说明
none
=> docs: add fastpb plugin description

content/en/docs/kitex/Tutorials/advanced-feature/codec_frugal.md, content/zh/docs/kitex/Tutorials/advanced-feature/codec_frugal.md
docs
en: remove duplicated title of frugal doc
zh: 移除 frugal 文档中多余的标题
none
=> docs: remove duplicated title of frugal doc

content/zh/docs/kitex/Tutorials/code-gen/fastpb.md
chore
en: fix fastpb zh typo
zh: 修复 fastpb 中文版标题格式
Fixes #314
=> chore: fix fastpb zh typo

content/en/_index.html, content/en/docs/netpoll/_index.md, content/en/docs/pilota/_index.md, content/en/docs/pilota/guide/_index.md, content/en/docs/pilota/guide/plugin.md, content/en/docs/volo/_index.md, content/zh/_index.html, content/zh/docs/netpoll/_index.md, content/zh/docs/volo/_index.md
chore: add pilota en doc & adjust projects sequence
en: add pilota en doc & adjust projects sequence
zh: 添加 pilota 英文文档 & 调整子项目在下拉框和网站footer的顺序
=> chore: add pilota en doc & adjust projects sequence

content/en/docs/kitex/Tutorials/advanced-feature/codec_frugal.md, content/zh/docs/kitex/Tutorials/advanced-feature/codec_frugal.md
docs
en: use frugal without codec code
zh: 使用 frugal 不生成编解码代码
none
=> docs(kitex): use frugal without codec code

content/en/docs/hertz/tutorials/framework-exten/service_discovery.md
…covery
docs: translate hertz tutorials/tutorials/framework-exten/service_dis…
en: translate hertz Service Registration and Service Discovery Extensions
zh: 翻译hertz 服务注册发现扩展
Fixes https://github.com/cloudwego/hertz/issues/200
=> docs: translate hertz tutorials/tutorials/framework-exten/service_discovery

content/zh/docs/hertz/tutorials/basic-feature/middleware/gzip.md, content/zh/docs/hertz/tutorials/basic-feature/middleware/i18n.md, content/zh/docs/hertz/tutorials/basic-feature/middleware/session.md
doc
en: add some middleware doc
zh: 添加hertz中间件文档
=> doc: add some middleware doc

content/en/docs/kitex/Tutorials/framework-exten/service_discovery.md, content/en/docs/kitex/Tutorials/service-governance/discovery.md, content/zh/docs/kitex/Tutorials/framework-exten/service_discovery.md, content/zh/docs/kitex/Tutorials/service-governance/discovery.md
docs: discovery.md
en:  Improve the description of service discovery
zh: 完善服务发现的讲述
=> docs(discovery.md): Improve the description of service discovery

content/zh/docs/hertz/tutorials/basic-feature/middleware/_index.md, content/zh/docs/hertz/tutorials/basic-feature/protocol.md, content/zh/docs/hertz/tutorials/basic-feature/route.md
doc
en:  add route doc
zh: 添加路由文档
=> doc: add route doc

content/zh/docs/hertz/tutorials/service-governance/open-telemetry.md
docs
zh: 在 Hertz 治理特性下添加 open-telemetry
=> docs: add open-telemetry docs for hertz

content/zh/community/_index.html, content/zh/community/past_activities/_index.md
=> docs(community): add hertz committer-skyenought

content/en/docs/kitex/Tutorials/advanced-feature/codec_frugal.md, content/en/docs/kitex/Tutorials/advanced-feature/invoker.md, content/zh/docs/kitex/Tutorials/advanced-feature/codec_frugal.md, content/zh/docs/kitex/Tutorials/advanced-feature/invoker.md
chore: fix some import in server sdk mode and codec_frugal
en: fix some import in server sdk mode and codec_frugal
zh: 修正了一些import 关于server sdk mode 和 codec_frugal
Fixes #335
=> chore: fix some import in server sdk mode and codec_frugal

content/zh/docs/hertz/tutorials/basic-feature/route.md
doc
en:  modify route doc
zh: 修改路由文档（调整错误的示例代码）
=> doc: modify route doc

content/en/docs/hertz/tutorials/service-governance/open-telemetry.md
docs
en: Add open-telemetry English doc
zh: 添加 open-telemetry 的英文文档
For https://github.com/cloudwego/hertz/issues/234
In the `What obs-opentelemetry implements`, I am consistent with https://github.com/hertz-contrib/obs-opentelemetry#feature. It is OK?
=> docs: translate open-telemetry

content/en/docs/hertz/tutorials/basic-feature/protocol/_index.md, content/en/docs/hertz/tutorials/basic-feature/protocol/websocket.md
docs
en: Translate the Websocket related content of the protocol section in the hertz documentation
zh: 翻译 hertz 文档中协议部分的Websocket相关内容
Fixes cloudwego/hertz#244
=> [docs]: translate hertz tutorials/basic-feature/protocol/websocket/

content/zh/blog/news/kitex_perf_optimize_practices/index.md
doc
en: misspelled word
zh: 单词拼写错误
=> doc: fix typo in Kitex blog

.gitmodules, README.md
chore: remove unuse file and description
en: remove unuse file and description, submodule is unused
zh: 移除submodule文件和描述
=> chore: remove unuse file and description

content/en/docs/hertz/tutorials/basic-feature/protocol/_index.md, content/en/docs/hertz/tutorials/basic-feature/protocol/websocket.md, content/zh/docs/hertz/tutorials/basic-feature/protocol/websocket.md
docs
en: add golang rendering for websocket.md
zh: 给websocket.md增加Go代码渲染
none of them
=> docs: add golang rendering for websocket.md

content/zh/docs/hertz/faq/_index.md
docs
en: update faq wiki of hertz
zh: 更新hertz faq页面
=> docs: update faq wiki

content/en/docs/hertz/reference/config.md, content/zh/docs/hertz/reference/config.md
docs
en: add server connection limitation demonstration（both for zh/en）
zh: 增加 server 最大连接数限制的说明（both for zh/en）
=> docs: add server connection limitation demonstration

content/en/docs/hertz/tutorials/basic-feature/middleware/pprof.md, content/zh/docs/hertz/tutorials/basic-feature/middleware/pprof.md
doc
en: add pprof doc
zh: 增加 pprof 文档中文部分
=> docs: add pprof doc

content/en/docs/kitex/Tutorials/basic-feature/limiting.md, content/zh/docs/kitex/Tutorials/basic-feature/limiting.md
docs
en: add rate limit note for grpc
zh: 添加grpc限流补充说明
=> docs: rate limit note

content/en/docs/hertz/tutorials/basic-feature/middleware/pprof.md, content/en/docs/hertz/tutorials/basic-feature/route.md, content/zh/docs/hertz/tutorials/basic-feature/middleware/pprof.md
fix
en: improve the route doc
zh: 修正route的部分文档内容
=> fix: improve the route doc

content/en/blog/_index.md, content/en/community/_index.html, content/en/cooperation/_index.md, content/zh/blog/_index.md, content/zh/community/_index.md, content/zh/community/meeting_notes/_index.md, content/zh/community/overview/_index.html, content/zh/community/past_activities/_index.md, content/zh/community/weekly_report/_index.md, content/zh/cooperation/_index.md
en: keep nav weight same
zh: 保持中英文导航顺序一致
=> chore: make nav weight same

content/en/docs/hertz/tutorials/basic-feature/middleware/jwt.md, content/zh/docs/hertz/tutorials/basic-feature/middleware/jwt.md
doc
en: improve jwt doc for Hertz
zh: 完善 Hertz 的 jwt 扩展的中文文档
=> docs: improve jwt doc

content/zh/docs/kitex/Tutorials/advanced-feature/generic-call/_index.md
docs
en: modify `Generic Call` zh title
zh: 修改泛化调用中文文档的标题
=> docs(Generic Call): modify `Generic Call` zh title

content/zh/docs/volo/volo-grpc/getting-started/part_2.md, content/zh/docs/volo/volo-grpc/getting-started/part_3.md, content/zh/docs/volo/volo-grpc/getting-started/part_4.md, content/zh/docs/volo/volo-thrift/getting-started/part_2.md, content/zh/docs/volo/volo-thrift/getting-started/part_4.md
docs(volo)
en: adapt to volo-0.2
=> docs(volo): adapt to volo-0.2

content/en/docs/hertz/tutorials/basic-feature/log.md, content/zh/docs/hertz/tutorials/basic-feature/log.md
doc 
en:  The preceding and subsequent descriptions do not match
zh: 前后描述不符合, 文档写的output.log, 代码为output.txt
[already review](https://github.com/cloudwego/cloudwego.github.io/pull/400)
=> update hertz log.md

content/en/docs/hertz/tutorials/basic-feature/middleware/swagger.md, content/zh/docs/hertz/tutorials/basic-feature/middleware/swagger.md
en:  improve swagger doc
zh: 改善 swagger 文档
=> doc: improve swagger doc

content/en/docs/hertz/tutorials/basic-feature/middleware/swagger.md, content/zh/docs/hertz/tutorials/basic-feature/middleware/swagger.md
docs
zh: 修复一些语序问题，使 swgger 的表达更加流畅
=> docs: make swagger.md read more smoothly

content/en/docs/hertz/tutorials/service-governance/sentinel.md, content/zh/docs/hertz/tutorials/service-governance/sentinel.md
docs
en: add sentinel docs
zh: 添加集成 sentinel 组件的相关文档
=> docs: add sentinel docs

content/en/docs/hertz/tutorials/basic-feature/middleware/keyauth.md, content/zh/docs/hertz/tutorials/basic-feature/middleware/keyauth.md
=> docs: add keyauth doc

content/en/docs/hertz/tutorials/basic-feature/middleware/basic-auth.md, content/zh/docs/hertz/tutorials/basic-feature/middleware/basic-auth.md
docs
en: improve docs for basic-auth middleware
zh: 完善basic-auth中间件的文档
=> doc: improve docs for basic-auth middleware

content/en/docs/kitex/Tutorials/advanced-feature/xds.md, content/zh/docs/kitex/Tutorials/advanced-feature/xds.md
doc
en: doc: update the example link of Proxyless
zh: doc: 更新 Proxyless 文档中的示例链接
=> doc: update the example link of Proxyless

content/en/docs/hertz/reference/json.md, content/zh/docs/hertz/reference/json.md
docs
en:   update the FAQ about sonic in Hertz
zh:  Hertz 中 sonic 已经升级到最新版，需要更新使用 sonic 时遇到的问题
Fixes #383
=> doc: update sonic faq

content/en/docs/kitex/Tutorials/framework-exten/middleware.md, content/zh/docs/kitex/Tutorials/framework-exten/middleware.md
docs
en: add context middleware introduce document
zh: 添加上下文中间件说明文档
=> docs: context middleware

content/en/docs/kitex/Tutorials/basic-feature/connection_type.md, content/zh/docs/kitex/Tutorials/basic-feature/connection_type.md
doc
en: doc: add description of MinIdlePerAddress in the connection type doc
zh: doc: 在连接类型的文档中添加 MinIdlePerAddress 的描述
=> doc: add description of MinIdlePerAddress in the connection type doc

assets/scss/_nav.scss, config.toml
feat
en: enable sidebar menu foldable
zh: 启用侧边栏的可折叠菜单
=> feat: enable sidebar menu foldable

content/en/docs/kitex/Tutorials/basic-feature/bizstatuserr.md, content/zh/docs/kitex/Tutorials/basic-feature/bizstatuserr.md
docs
en:  docs: add business exception introductions
zh:  docs: 添加自定义异常说明文档
=> docs: add business exception introductions

content/en/about/_index.html, content/en/blog/_index.md, content/zh/community/_index.md, i18n/en.toml, i18n/zh.toml, layouts/404.html, layouts/partials/handle-version-switch-404.html
feat
en: add i18n 404 page
zh: 添加 i18n 自适应的 404 界面
=> feat: add i18n 404 page

content/en/docs/hertz/tutorials/framework-exten/log.md, content/zh/docs/hertz/tutorials/framework-exten/log.md
docs
en: Due to the new logger extension, modify the log extension document.
zh: 由于新增 logger 拓展，因此修改日志拓展文档。
None.
=> docs: refactor hlog

.editorconfig
chore: change editorconfig
en: change editorconfig config
zh: 修改 editconfig配置
=> chore: change editorconfig

assets/scss/_code.scss, layouts/partials/hooks/body-end.html, static/js/copy-code-button.js
en: copy code button
zh: 代码复制按钮
=> feat: copy code button

content/zh/blog/news/Hertz_Benchmark/index.md, content/zh/docs/motore/overview/_index.md
doc & fix
en: small fix on hertz blog and motore doc
zh: hertz blog 优化 & 修复 motore 文档 typo
=> fix: small fix on hertz blog and motore doc

content/en/docs/hertz/tutorials/basic-feature/hooks.md, content/zh/docs/hertz/tutorials/basic-feature/hooks.md
docs
en: add hooks docs for Hertz
zh: 为 Hertz 增加 hooks 相关文档
=> docs: add docs for hooks

content/en/docs/kitex/Tutorials/advanced-feature/profiler.md, content/zh/docs/kitex/Tutorials/advanced-feature/profiler.md
docs
en: introduce request profiler features
zh: 介绍请求成本度量功能
=> docs: request profiler

content/en/docs/hertz/tutorials/framework-exten/log.md, content/zh/docs/hertz/tutorials/framework-exten/log.md
docs
en: 为日志文档新增 zerolog 。
zh: add zerolog to improve log.md.
None.
=> docs: add zerolog to improve log.md

layouts/blog/content.html, layouts/partials/hooks/body-end.html, static/js/outbound-link.js
en: addthis share button and outbound link in blank
zh: addthis分享按钮和站外链接在新窗口打开
=> feat: addthis and outbound link

content/en/docs/hertz/tutorials/framework-exten/service_discovery.md, content/zh/docs/hertz/tutorials/framework-exten/service_discovery.md
fix
```go
func (c *Client) Use(mws ...Middleware)
```
```go
func Discovery(resolver discovery.Resolver, opts ...ServiceDiscoveryOption) func(next client.Endpoint) client.Endpoint
```
```go
func WithLoadBalanceOptions(lb loadbalance.Loadbalancer, options loadbalance.Options) ServiceDiscoveryOption
```
As can be seen from the above function signature, we should use
```go
cli.Use(sd.Discovery(r, sd.WithLoadBalanceOptions(***,***)))
```
not
```go
cli.Use(sd.Discovery(r),sd.WithLoadBalanceOptions(***,***))
```
None.
=> fix: reslove loadbalance code bug

content/en/docs/hertz/tutorials/basic-feature/middleware/jwt.md, content/zh/docs/hertz/tutorials/basic-feature/middleware/jwt.md
docs
en: Refine the extraction of user information in Sample Code in jwt readme
zh: 完善 jwt 文档中的代码示例，补充提取用户信息的相关内容
=> docs: optimize official documents for jwt

content/en/docs/hertz/tutorials/basic-feature/middleware/i18n.md, content/zh/docs/hertz/tutorials/basic-feature/middleware/i18n.md
docs
en: upadate i18n docs
zh: 更新 i18n 文档
=> docs: update i18n docs

content/en/docs/hertz/tutorials/basic-feature/proxy.md, content/zh/docs/hertz/tutorials/basic-feature/proxy.md
en: improve proxy docs
zh: 优化代理文档
=> docs: improve proxy docs

assets/scss/_sidebar-tree.scss
style
en: adjust the height of td-sidebar-nav
zh: 调整 sidebar nav 的高度, 使其符合感官
before:
at now:
=> style: adjust the height of td-sidebar-nav

content/en/blog/news/Kitex_perf_optimize_practices/index.md, content/en/blog/news/Kitex_performance_testing/index.md, content/en/blog/news/article_to_learn_about_CloudWeGo/index.md, content/en/blog/news/bytedance_gonet_practice/index.md, content/en/blog/news/open_source_announcement/index.md
docs & optimize
en: optimize en blogs with keywords and desscription
zh: 优化英文博客，添加关键字和描述
=> optimize(docs): optimize en blogs with keywords and description

content/en/docs/hertz/tutorials/basic-feature/middleware/jwt.md, content/zh/docs/hertz/tutorials/basic-feature/middleware/jwt.md
docs
en: optimzie hertz-jwt docs for the extraction of token information
zh: 调整文档布局，使之更容易理解如何从 token 提取用户信息
=> docs: optimze hertz-jwt docs

content/en/docs/kitex/Tutorials/advanced-feature/profiler.md, content/zh/docs/kitex/Tutorials/advanced-feature/profiler.md
docs
en: docs: add profiler notes and rename title
zh: docs: 添加 profiler 注意事项，重新命名标题
=> docs: add profiler notes and rename title

content/en/docs/hertz/tutorials/basic-feature/middleware/gzip.md, content/zh/docs/hertz/tutorials/basic-feature/middleware/gzip.md
docs
en:  update gzip docs
zh: 更新 gzip 文档
=> docs: update gzip docs

content/zh/blog/news/Kitex_Proxyless_OpenTelemetry/index.md
=> docs: improve Kitex_Proxyless blog

content/en/docs/hertz/tutorials/basic-feature/middleware/swagger.md, content/zh/docs/hertz/tutorials/basic-feature/middleware/swagger.md
en: add swagger init param
zh: 增加swag init 参数描述
=> feat: add swagger init param

content/en/cooperation/_index.md, content/zh/cooperation/_index.md
chore: bluebook download and event
en: bluebook download and ga event
zh: 项目介绍下载和ga事件上报。
=> chore: bluebook download and event

content/en/docs/hertz/tutorials/basic-feature/middleware/secure.md, content/zh/docs/hertz/tutorials/basic-feature/middleware/secure.md
docs
en: add secure docs
zh: 添加 secure 中间件的文档
=> docs: add secure docs

content/en/docs/hertz/reference/config.md, content/zh/docs/hertz/reference/config.md
What type of PR is this?
docs
What this PR does / why we need it (en: English/zh: Chinese):
en: add writeTimeout docs
zh: 添加 writeTimeout 的文档 
Which issue(s) this PR fixes:
https://github.com/cloudwego/hertz/issues/377
=> doc: add WithWriteTimeout

content/en/docs/hertz/tutorials/basic-feature/protocol/tls.md, content/zh/docs/hertz/tutorials/basic-feature/protocol/tls.md
optimize
en: refine the description of unsupported tls
zh: 完善 netpoll 不支持的TLS 的描述
=> optimize: refine the description of unsupported tls

config.toml
chore: add footer link
en: add footer link
zh: 增加底部链接
=> chore: footer link

content/en/docs/hertz/tutorials/basic-feature/middleware/sentry.md, content/zh/docs/hertz/tutorials/basic-feature/middleware/sentry.md
docs
en: add hertzsentry docs
zh: 添加 hertzsentry 文档
=> docs: add hertzsentry docs

content/zh/docs/hertz/tutorials/basic-feature/middleware/secure.md
fix
en: modify secure.md weight
zh: 调整 secure.md 权重
=> fix: modify secure.md weight

content/en/docs/hertz/tutorials/basic-feature/middleware/csrf.md, content/zh/docs/hertz/tutorials/basic-feature/middleware/csrf.md
docs
en: Added documentation for the `CSRF` middleware.
zh: 添加了 `CSRF` 中间件的文档。
Fixes https://github.com/cloudwego/hertz/issues/422
=> docs: add csrf docs

content/en/docs/hertz/tutorials/basic-feature/middleware/csrf.md, content/zh/docs/hertz/tutorials/basic-feature/middleware/csrf.md
docs
en: Fixed errors in the documentation and handled possible errors when exporting logs
zh: 修改了文档中的错误并处理了输出日志时可能产生的错误
none
=> doc: update csrf docs

content/en/docs/hertz/tutorials/basic-feature/graceful-shutdown.md, content/zh/docs/hertz/tutorials/basic-feature/graceful-shutdown.md
en: optimize graceful_shutdown docs
zh: 完善优雅退出文档
https://github.com/cloudwego/hertz/issues/415
=> docs: optimize graceful_shutdown docs

content/en/docs/hertz/tutorials/basic-feature/route.md, content/zh/docs/hertz/tutorials/basic-feature/route.md
docs
en:  supplement route English documents，add a demonstration for registering static file routes
zh:  补充路由的英文文档，添加用于注册静态文件路由的使用
=> docs: supplement route English documents

content/en/docs/kitex/Tutorials/basic-feature/transport_protocol.md, content/zh/docs/kitex/Tutorials/basic-feature/transport_protocol.md
fix
en: remove unused comment of transport_protocol doc
zh: 删除传输协议文档中无用的注释
=> style: remove unused comment of transport_protocol doc

content/en/docs/hertz/getting-started/_index.md, content/en/docs/hertz/tutorials/basic-feature/route.md, content/zh/docs/hertz/getting-started/_index.md, content/zh/docs/hertz/tutorials/basic-feature/route.md
docs
en: optimize route description about matching and fix getting started hertz-demo
zh: 优化路由文档中关于路由匹配的描述 和 修复hertz快速开始中hertz-demo
https://github.com/cloudwego/cloudwego.github.io/issues/472 & https://github.com/cloudwego/cloudwego.github.io/issues/476
=> docs: optimize route description about matching and fix getting started hertz-demo

content/en/docs/hertz/tutorials/basic-feature/middleware/recovery.md, content/zh/docs/hertz/tutorials/basic-feature/middleware/recovery.md
docs
en: docs: add hertz recovery docs.
zh: 为hertz recovery中间件新增文档。
=> docs: add hertz recovery docs

content/en/docs/hertz/tutorials/basic-feature/middleware/session.md, content/zh/docs/hertz/tutorials/basic-feature/middleware/session.md
en: enrich session doc, add distributed session part, update deprecated functions
zh: 补充 Session 中间件文档，添加分布式 Session 代码示例，更新弃用函数
null
=> docs: enrich session doc, add distributed session part

content/en/docs/kitex/Tutorials/advanced-feature/metainfo.md, content/zh/docs/kitex/Tutorials/advanced-feature/metainfo.md
docs
en: add kitex grpc metadata docs
zh: 添加 kitex grpc metadata 使用文档
=> docs: add kitex grpc metadata docs

content/en/docs/hertz/tutorials/example/_index.md, content/zh/docs/hertz/tutorials/example/_index.md
en: enrich the introduction of hertz-examples
zh: 补充代码示例部分的介绍
null
=> docs: enrich the introduction of hertz-examples

content/en/docs/volo/volo-grpc/getting-started/part_3.md, content/en/docs/volo/volo-grpc/getting-started/part_4.md, content/en/docs/volo/volo-thrift/getting-started/part_3.md, content/en/docs/volo/volo-thrift/getting-started/part_4.md, content/zh/docs/volo/guide/discovery_lb.md, content/zh/docs/volo/guide/metadata.md, content/zh/docs/volo/guide/observability.md, content/zh/docs/volo/guide/with_callopt.md, content/zh/docs/volo/volo-grpc/getting-started/part_3.md, content/zh/docs/volo/volo-grpc/getting-started/part_4.md, content/zh/docs/volo/volo-thrift/getting-started/part_3.md, content/zh/docs/volo/volo-thrift/getting-started/part_4.md
en: adapt to volo 0.3.0
zh: 更新文档
=> docs(volo): adapt to volo 0.3.0

content/en/docs/hertz/tutorials/basic-feature/middleware/jwt.md, content/zh/docs/hertz/tutorials/basic-feature/middleware/jwt.md
en: add description of ParseOptions
zh: 添加 ParseOptions 选项的描述
null
=> docs: enrich jwt configuration info

content/en/docs/hertz/tutorials/basic-feature/middleware/requestid.md, content/zh/docs/hertz/tutorials/basic-feature/middleware/requestid.md
en: 
zh: 更新requestid generator 的函数签名
null
=> docs: update function signatures of requestid

content/en/docs/hertz/tutorials/basic-feature/protocol/websocket.md, content/zh/docs/hertz/tutorials/basic-feature/protocol/websocket.md
docs
en: optimize hertz websocket docs
zh: 优化 hertz websocket 的文档
=> docs: optimize hertz websocket docs

content/en/docs/hertz/tutorials/basic-feature/middleware/cors.md, content/zh/docs/hertz/tutorials/basic-feature/middleware/cors.md
docs
en:  optimize cors docs
zh: 优化 cors 中间件的文档
=> docs: optimize cors docs

content/zh/docs/hertz/reference/migration.md
docs
en: Add documentation for hertz migration
zh: 添加hertz的迁移文档
=> docs: add hertz migration docs

content/en/docs/hertz/tutorials/basic-feature/adaptor.md, content/zh/docs/hertz/tutorials/basic-feature/adaptor.md
en: add docs for Hertz adaptor
zh: 添加 Hertz adaptor 的文档
Fixes https://github.com/cloudwego/hertz/issues/506
=> docs: add hertz adaptor

content/en/docs/hertz/tutorials/toolkit/toolkit.md, content/zh/docs/hertz/tutorials/toolkit/toolkit.md
docs: Add some notes for hz cli toolkit on using Windows environment.
en: I found some problems when using the `hz` tool; they are not bugs but some subtle environment-related details that anyone doing the same thing as me would face. So I added some notes to it.
zh:
=> docs: Add hz cli notes on using Windows

content/zh/blog/releases/Hertz/release-v050.md
docs
en:  add release note for hertz v0.5.0
zh: 新增 hertz v0.5.0 版本解读
=> docs: add release note for hertz v0.5.0

content/en/docs/kitex/Getting started/_index.md
en: 
Improve the quickstart doc using [deepl write](https://www.deepl.com/write) , which help fix grammar issues.
As an experiment, I only modify the part before the `Tutorial` chapter.
zh:
用[deepl write](https://www.deepl.com/write) 优化 quickstart 文档的语法
=> docs: improve quickstart doc using deepl write

content/en/docs/hertz/tutorials/basic-feature/middleware/jwt.md, content/zh/docs/hertz/tutorials/basic-feature/middleware/jwt.md
zh: 添加 jwt 对 form token 的支持
null
=> docs: add support form token for jwt mw

content/en/blog/releases/Hertz/release-v050.md
docs
en: add english release note for hertz v0.5.0
zh: 新增 hertz v0.5.0 版本英文解读
None.
=> docs: add english release note for hertz v0.5.0

content/en/docs/hertz/tutorials/basic-feature/proxy.md, content/zh/docs/hertz/tutorials/basic-feature/proxy.md
optimize
en: improve reverse proxy doc
zh: 优化反向代理文档
No
=> optimize: improve reverse proxy doc

content/en/docs/hertz/tutorials/basic-feature/proxy.md
style
en: fix wrong code and delete some example links
zh: 修复错误代码并删除一些示例链接
None.
=> style: fix wrong code and delete some example links

content/en/docs/hertz/tutorials/example/_index.md, content/zh/docs/hertz/tutorials/example/_index.md
=> docs: add hz part for hertz example

content/en/docs/hertz/reference/json.md, content/zh/docs/hertz/reference/json.md
optimize
en: add conditional compilation doc for json
zh: 新增关于 json 条件编译的内容
https://github.com/cloudwego/hertz/issues/281
=> optimize: add conditional compilation for json

content/en/docs/hertz/tutorials/basic-feature/middleware/casbin.md, content/zh/docs/hertz/tutorials/basic-feature/middleware/casbin.md
docs
en:  add casbin middleware
zh:
=> docs: add casbin middleware

content/en/docs/hertz/tutorials/basic-feature/middleware/etag.md, content/zh/docs/hertz/tutorials/basic-feature/middleware/etag.md
=> docs: optimize etag doc

content/en/docs/kitex/Tutorials/service-governance/tracing.md
chore: remove unused desc
en: remove unused desc
zh: 移除多余的描述
=> chore: remove unused desc

content/en/docs/hertz/getting-started/_index.md, content/en/docs/hertz/overview/_index.md
docs
en: optimise hertz overview & getting-started
zh: 优化 hertz overview & getting-started 英文文档
=> docs: optimise hertz overview & getting-started

content/en/blog/releases/Volo/release-v032.md, content/zh/blog/releases/Volo/release-v032.md
docs
en: add volo release notes for v0.3.2
zh: 添加英文版 Volo v0.3.2 发版说明
=> docs(en): add volo release notes for v0.3.2

content/en/docs/hertz/reference/config.md, content/zh/docs/hertz/reference/config.md
=> docs: supplement server configuration

content/en/docs/kitex/Getting started/_index.md
Translation of:
- https://github.com/cloudwego/cloudwego.github.io/pull/542
- https://github.com/cloudwego/cloudwego.github.io/pull/543
optimize
en: translate 2 previously merged PR
zh:
- https://github.com/cloudwego/cloudwego.github.io/pull/542
- https://github.com/cloudwego/cloudwego.github.io/pull/543
=> optimize: thrift version and settings.py issue

README.md
chore: Hugo install notice
en: chore: Hugo install notice
zh: Hugo 安装提示
=> chore: hugo install notice

content/en/docs/cwgo/tutorials/layout/_index.md
docs
en: update url in cwgo Getting Started
zh: 更新 cwgo Getting Started 中的 url
=> docs: update url in cwgo Getting Started

content/zh/docs/cwgo/tutorials/layout/_index.md
docs
en: update url in cwgo layout zh docs
zh: 更新 cwgo 中文 layout 文档链接
=> docs: update url in cwgo layout zh docs

content/en/blog/news/Hertz_Benchmark/index.md, content/zh/blog/news/Hertz_Benchmark/index.md
docs(blog)
en: translate getting-started-with-hertz-performance-testing-guide
zh: 翻译<HTTP 框架 Hertz 实践入门：性能测试指南>
=> docs(blog): translate getting-started-with-hertz-performance-testing-guide

content/zh/docs/hertz/tutorials/toolkit/usage/cautions.md
=> Fix(docs): fix typo in hertz toolkit cautions.md

content/en/docs/hertz/tutorials/basic-feature/middleware/cache.md, content/zh/docs/hertz/tutorials/basic-feature/middleware/cache.md
docs
en: add docs for hertz-cache
zh: 为 hertz-cache 中间件增加中英文文档
=> docs: add hertz-cache docs

content/en/docs/kitex/Tutorials/basic-feature/bizstatuserr.md, content/en/docs/kitex/Tutorials/basic-feature/fallback.md, content/en/docs/kitex/Tutorials/basic-feature/logging.md, content/en/docs/kitex/Tutorials/basic-feature/tracing.md, content/zh/docs/kitex/Tutorials/basic-feature/bizstatuserr.md, content/zh/docs/kitex/Tutorials/basic-feature/fallback.md, content/zh/docs/kitex/Tutorials/basic-feature/logging.md, content/zh/docs/kitex/Tutorials/basic-feature/tracing.md
docs
en: docs(kitex): add doc for kitex fallback feature
zh:
=> docs(kitex): add doc for kitex fallback feature

content/zh/docs/kitex/Tutorials/code-gen/custom_tpl.md
docs
en:  add custom template for kitex docs
zh: 为 kitex 添加自定义模板文档
=> feat: add custom template for kitex docs

content/en/docs/kitex/Tutorials/code-gen/custom_tpl.md, content/zh/docs/kitex/Tutorials/code-gen/custom_tpl.md
docs
en: reserve English version cunstom tpl docs and rich Chinese docs
zh: 保留英文自定义模板的文档并且丰富中文文档
=> feat: reserve English version cunstom tpl docs and rich Chinese docs

content/en/docs/kitex/Tutorials/options/client_options.md, content/zh/docs/kitex/Tutorials/options/client_options.md
docs
en: docs(gRPC): add doc for grpc TLS option
zh:
=> docs(gRPC): add doc for grpc TLS option

content/en/docs/kitex/Getting started/_index.md
docs
en: Make the format of the command `cd kitex-examples/hello` for `Run with go` consistent with other commands.
zh: 使 `Run with go` 的 `cd kitex-examples/hello` 命令的格式与其他命令一致。
=> chore: format the command for `Run with go`

content/zh/docs/kitex/Tutorials/code-gen/code_generation.md
docs
en:  optimize code generation tool docs
zh:  重新整理完善了命令行工具的文档
=> docs: optimize code generation tool docs

content/en/docs/hertz/tutorials/toolkit/usage/usage-protobuf.md, content/en/docs/hertz/tutorials/toolkit/usage/usage-thrift.md, content/zh/docs/hertz/tutorials/toolkit/usage/usage-protobuf.md, content/zh/docs/hertz/tutorials/toolkit/usage/usage-thrift.md
feat
en: add the code create way is not under GOPATH(thrift)
zh:提供非GOPATH下的项目生成代码的步骤
=> feat:add the code create way is not under GOPATH

content/en/docs/netpoll/Overview/_index.md, content/zh/docs/netpoll/Overview/_index.md
chore
en: update netpoll overview
zh: 更新 Netpoll 概览
=> chore: update netpoll overview

content/en/docs/hertz/tutorials/framework-exten/response_writer.md, content/zh/docs/hertz/tutorials/framework-exten/response_writer.md
en: add en docs for response writer ext
zh: 添加response writer扩展的英文文档
related to https://github.com/cloudwego/hertz/issues/656
=> doc(hertz): add response writer ext doc

content/zh/community/overview/_index.html, content/zh/community/past_activities/_index.md
docs
en: update the latest activity
zh: 更新最新活动和往期活动
=> docs(community): update the latest activity

content/en/blog/releases/Kitex/release-v040.md, content/en/blog/releases/Kitex/release-v043.md, content/en/blog/releases/Kitex/release-v050.md, content/zh/blog/releases/Kitex/release-v040.md, content/zh/blog/releases/Kitex/release-v043.md, content/zh/blog/releases/Kitex/release-v050.md
=> docs(kitex): add release info for version v0.5.0

content/en/blog/releases/Kitex/release-v050.md
=> docs(kitex): update release info for version v0.5.0

content/en/docs/hertz/tutorials/basic-feature/middleware/swagger.md, content/zh/docs/hertz/tutorials/basic-feature/middleware/swagger.md
=> fix: fix typo in hertz swagger middleware

content/en/docs/kitex/Tutorials/basic-feature/loadbalance.md, content/zh/docs/kitex/Tutorials/basic-feature/loadbalance.md
docs
en: docs: introduce weighted round robin loadbalancer
zh: docs: 介绍基于权重的轮询负载均衡器
=> docs: introduce weighted round robin loadbalancer

content/en/docs/hertz/tutorials/basic-feature/middleware/access-log.md, content/zh/docs/hertz/tutorials/basic-feature/middleware/access-log.md
docs 
en: 
zh: 添加 hertz 访问日志文档
https://github.com/cloudwego/hertz/issues/487
=> doc(hertz): add access log doc

content/en/docs/cwgo/getting-started/_index.md, content/zh/docs/cwgo/getting-started/_index.md
fix
en: fix lost link of cwgo wiki
zh: 修复 cwgo 的无效链接
Fixes #581
=> fix(cwgo): fix lost link of cwgo wiki

content/zh/blog/releases/Volo/release-v030.md, content/zh/blog/releases/Volo/release-v032.md, content/zh/blog/releases/Volo/release-v041.md
=> volo 0.4 release note

content/en/docs/kitex/Tutorials/basic-feature/fallback.md
docs
en: translate kitex-fallback doc based on Chinese doc
zh:
cloudwego/kitex#855
=> docs(kitex): translate kitex-fallback doc based on Chinese doc

.github/workflows/push-check.yml, content/en/blog/news/Kitex_perf_optimize_practices/index.md, content/en/blog/releases/Volo/release-v021.md, content/en/docs/hertz/tutorials/service-governance/service_discovery.md, content/en/docs/kitex/Tutorials/advanced-feature/generic-call/thrift_idl_annotation_standards.md, content/en/docs/kitex/Tutorials/basic-feature/circuitbreaker.md, content/en/docs/volo/overview/_index.md, content/zh/blog/news/Rust_or_Go/index.md, content/zh/community/meeting_notes/2022-03-11/_index.md, content/zh/docs/hertz/tutorials/service-governance/service_discovery.md, content/zh/docs/kitex/Tutorials/advanced-feature/generic-call/thrift_idl_annotation_standards.md
ci
en: fix ci typos and missed typos ([ci should failed like](https://github.com/a631807682/cloudwego.github.io/actions/runs/4508702857/jobs/7937655444))
zh: 修复ci typos和遗漏的拼写错误  ([ci 如果生效应该失败](https://github.com/a631807682/cloudwego.github.io/actions/runs/4508702857/jobs/7937655444))
=> ci: fix typos workflow

layouts/partials/hooks/body-end.html, static/js/navScroll.js
en: Scroll to the active item when the navbar is too long
zh: 导航栏太长的时候滚动到当前导航
=> feat: Scroll to the active item when the navbar is too long

content/en/blog/releases/Volo/release-v041.md
docs: add english release note of volo 0.4.1
=> add english release note of volo 0.4.1

content/en/blog/news/bytedance_gonet_practice/index.md, content/en/docs/netpoll/Overview/_index.md, content/zh/blog/news/bytedance_gonet_practice/index.md, content/zh/docs/netpoll/Overview/_index.md
docs
en: docs: declare netpoll delay issue and rm outdated info
zh: docs: 说明 netpoll延迟问题以及删除过时信息
=> docs: declare netpoll delay issue and rm outdated info

content/zh/docs/kitex/Tutorials/code-gen/custom_tpl.md
docs
en: optimize custom tpl docs
zh: 优化自定义模板文档
=> optimzie: custom_tpl docs

content/en/docs/kitex/Tutorials/code-gen/validator.md, content/zh/docs/kitex/Tutorials/code-gen/validator.md
docs: add `installation` part in kitex/tutorials/code-gen/validator with en/zh docs
en: update validator doc with installation
zh: 在 validator 文档中增加安装说明
Fix #586
=> doc: update validator.md in en/zh tutorial docs

content/en/blog/releases/Kitex/release-v005.md, content/en/docs/cwgo/getting-started/_index.md, content/en/docs/cwgo/tutorials/cli/_index.md, content/en/docs/hertz/getting-started/_index.md, content/en/docs/hertz/overview/_index.md, content/en/docs/hertz/tutorials/basic-feature/protocol/_index.md, content/en/docs/hertz/tutorials/observability/log.md, content/en/docs/hertz/tutorials/observability/monitoring.md, content/en/docs/kitex/FAQ/_index.md, content/en/docs/netpoll/Overview/_index.md, content/zh/blog/news/Go_HTTP_Hertz_Design/index.md, content/zh/blog/news/article_to_learn_about_CloudWeGo/index.md, content/zh/blog/releases/Kitex/release-v005.md, content/zh/docs/cwgo/getting-started/_index.md, content/zh/docs/cwgo/tutorials/cli/_index.md, content/zh/docs/hertz/getting-started/_index.md, content/zh/docs/hertz/overview/_index.md, content/zh/docs/kitex/FAQ/_index.md, content/zh/docs/netpoll/Overview/_index.md
en:  fix link error
zh:  修正一些链接错误
=> chore: fix link error

content/en/docs/kitex/FAQ/_index.md, content/en/docs/kitex/Getting started/_index.md, content/en/docs/kitex/Tutorials/code-gen/code_generation.md, content/zh/docs/kitex/FAQ/_index.md, content/zh/docs/kitex/Getting started/_index.md, content/zh/docs/kitex/Tutorials/code-gen/code_generation.md
=> docs: update kitex command docs about windows

content/zh/docs/hertz/getting-started/_index.md
=> docs(hertz): update quick start

content/en/blog/releases/Kitex/release-v052.md, content/zh/blog/releases/Kitex/release-v052.md
=> doc: add release for v0.5.2

.github/ISSUE_TEMPLATE/DOCS_UPDATE.md, .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md, .github/ISSUE_TEMPLATE/ISSUE_REPORT.md
en: issue template
zh(optional): 更新issue模板
#626
=> chore: issue template

content/en/docs/hertz/tutorials/observability/log.md
=> fix: fix the wrong address for the log  document

content/en/_index.html, content/zh/_index.html
chore
给原始用户添加网站链接
en: add link to orginal users
zh(optional):
=> chore: add link to orginal users

content/en/docs/kitex/Tutorials/code-gen/custom_tpl.md, content/zh/docs/kitex/Tutorials/code-gen/custom_tpl.md
feat
更新 kitex 自定义模板文档
en: update kitex custom template docs  
zh(optional): 更新 kitex 自定义模板文档
=> feat: update custom template docs

content/en/docs/hertz/tutorials/observability/log.md, content/zh/docs/hertz/tutorials/observability/log.md
feat
安静模式
en: add silentmode docs for Hertz
zh(optional): 增加安静模式文档
https://github.com/cloudwego/hertz/pull/745
=> feat: silent mode

content/en/docs/hertz/tutorials/observability/log.md, content/zh/docs/hertz/tutorials/observability/log.md
docs
en: add FAQ in docs of observability
zh(optional): 丰富了可观测性的文档
=> docs: add FAQ in docs of observability

content/en/docs/kitex/Tutorials/advanced-feature/generic-call/_index.md, content/zh/docs/kitex/Tutorials/advanced-feature/generic-call/_index.md
=> fix: fix a link in docs

content/en/docs/hertz/tutorials/toolkit/more-feature/client.md, content/zh/docs/hertz/tutorials/toolkit/more-feature/client.md
docs 
- 更新 hz client 使用说明
pr for https://github.com/cloudwego/hertz/pull/782
=> docs: update hz's client usage

content/en/docs/kitex/Tutorials/advanced-feature/metainfo.md, content/zh/docs/kitex/Tutorials/advanced-feature/metainfo.md
doc
zh: doc: 修改 metainfo 文档
en:
zh(optional): 
#647
=> doc: revise the example of metainfo

content/en/docs/hertz/tutorials/basic-feature/constants.md, content/zh/docs/hertz/tutorials/basic-feature/constants.md
=> feat: add constants docs

content/en/blog/news/open_source_volo/index.md, content/en/docs/motore/overview/_index.md, content/en/docs/volo/volo-grpc/getting-started/part_2.md, content/en/docs/volo/volo-thrift/getting-started/part_2.md, content/zh/blog/news/open_source_volo/index.md, content/zh/docs/volo/volo-grpc/getting-started/part_2.md, content/zh/docs/volo/volo-thrift/getting-started/part_2.md
replace type_alias_impl_trait with type_alias_impl_trait
en:
zh(optional):
=> docs(volo): use type_alias_impl_trait

content/zh/docs/kitex/Tutorials/service-governance/circuitbreaker.md
为 kitex/circuitbreaker 增加更具体的使用示例
en:
zh(optional): 
https://github.com/cloudwego/cloudwego.github.io/issues/663
=> docs: add a detailed example for kitex/circuitbreaker

content/en/docs/kitex/Tutorials/service-governance/circuitbreaker.md
为 (en) kitex/circuitbreaker 增加更具体的使用示例
en:
zh(optional): 
https://github.com/cloudwego/cloudwego.github.io/issues/663
=> docs: add a detailed example for kitex/circuitbreaker (en)

config.toml, layouts/partials/page-meta-links.html
chore: link the project issue to a specific project
en: chore: link the project issue to a specific project
zh(optional): project issue链接到特定仓库
=> chore: link the project issue to a specific project

layouts/partials/page-meta-links.html
chore: remove debug print
en: remove the print information introduced by the previous PR
zh(optional): 删除上一个pr引入的debug打印信息
=> chore: remove debug print

content/en/docs/cwgo/tutorials/cli/_index.md, content/en/docs/cwgo/tutorials/db/_index.md, content/zh/docs/cwgo/tutorials/cli/_index.md, content/zh/docs/cwgo/tutorials/db/_index.md
docs
docs(cwgo): update db docs
docs(cwgo): 更新db相关命令文档
en:
zh(optional):
=> docs(cwgo): update db docs

content/en/docs/cwgo/tutorials/layout/_index.md, content/zh/docs/cwgo/tutorials/layout/_index.md
=> docs: improve cwgo document

content/en/docs/kitex/Tutorials/advanced-feature/error_handler.md
=> docs(kitex): update error_handler.md(en)

content/zh/docs/kitex/Tutorials/advanced-feature/error_handler.md
=> docs(kitex): update error_handler.md

content/en/docs/kitex/Tutorials/options/call_options.md, content/en/docs/kitex/Tutorials/options/server_options.md, content/zh/docs/kitex/Tutorials/options/call_options.md, content/zh/docs/kitex/Tutorials/options/server_options.md
fix sub-titles level in does, start with ## and then follow with ###
=> fix:sub-titles level, start with ## and then follow with ###

content/en/docs/hertz/getting-started/_index.md, content/en/docs/hertz/tutorials/toolkit/usage/usage.md, content/zh/docs/hertz/getting-started/_index.md, content/zh/docs/hertz/tutorials/toolkit/usage/usage.md
It is a small improvement of Hertz docs `Getting Started` and `hz basic usage` according to issue #682.
docs
Fixes #682.
=> docs: improvement of Hertz according to issue #682.

content/en/docs/kitex/Tutorials/framework-exten/codec.md
=> docs: WithPayloadCodec (en)

content/en/_index.html, content/zh/_index.html
=> optimize: update homepage description

content/zh/docs/hertz/tutorials/toolkit/usage/annotation.md
=> fix: grammar err

content/en/docs/kitex/Tutorials/service-governance/retry.md
en: Make "dynamic configuration" more comprehensive and fix reference of "3.3"
zh(optional):
=> Update kitex retry.md

content/zh/docs/kitex/Getting started/_index.md
en: elaborate more on kitex client example
zh(optional):
=> Update kitex getting started

content/en/docs/kitex/Tutorials/advanced-feature/generic-call/_index.md, content/zh/docs/kitex/Tutorials/advanced-feature/generic-call/_index.md
=> docs: update  code example in kitex-generic call

content/en/docs/kitex/Tutorials/advanced-feature/generic-call/_index.md, content/zh/docs/kitex/Tutorials/advanced-feature/generic-call/_index.md
=> docs: update code example and add note in kitex-generic call 

content/zh/docs/kitex/Tutorials/advanced-feature/generic-call/_index.md
=> docs: update code example in IDL 

content/en/docs/hertz/tutorials/toolkit/usage/usage-thrift.md, content/zh/docs/hertz/tutorials/toolkit/usage/usage-thrift.md
docs
优化 hertz usage-thrift 文档初始化部分说明
en:
zh(optional):
=> docs(hertz): update usage-thrift

content/zh/about/_index.html
=> chore: update about page

content/zh/about/_index.html, content/zh/docs/kitex/Tutorials/basic-feature/connection_type.md
=> chore: fix space and typo

content/en/docs/kitex/Getting started/_index.md
en: elaborate more on kitex client example
zh(optional):
=> Update kitex getting started en

content/en/docs/kitex/Tutorials/advanced-feature/generic-call/_index.md, content/zh/docs/kitex/Tutorials/advanced-feature/generic-call/_index.md
=> docs:update code example in kitex-generic call 

content/en/docs/hertz/tutorials/basic-feature/protocol/http2.md, content/zh/docs/hertz/tutorials/basic-feature/protocol/http2.md
zh(optional): 
修复 http2 中的输入错误, MacOS 下 Option+C  
#734
=> fix type error

content/en/docs/hertz/tutorials/example/_index.md, content/zh/docs/hertz/tutorials/example/_index.md
docs
对其 hertz-examples和文档中的示例部分
en: docs: alignment hertz-examples and document
zh(optional):  docs: 对其 hertz-examples和文档中的示例部分
=> docs: alignment hertz-examples and document

content/en/docs/hertz/getting-started/_index.md, content/zh/docs/hertz/getting-started/_index.md
docs
快速开始的文档中补充不使用hz的用法
en: docs: supplement do not use hz description in getting-started
zh(optional):  快速开始的文档中补充不使用hz的用法
=> docs: supplement do not use hz description in getting-started

content/en/_index.html, content/zh/_index.html
=> fix: fix wrong link for shmipc

content/en/about/_index.html
thrfitgo -> thriftgo
docs
en:
zh(optional):
=> fix typo in _index.html

content/en/docs/hertz/tutorials/basic-feature/client.md, content/zh/docs/hertz/tutorials/basic-feature/client.md
docs
客户端请求超时函数使用的补充说明
en:docs: supplement description in client request timeout
zh(optional): 客户端请求超时函数使用的补充说明
=> docs: supplement description in client request timeout

content/en/docs/hertz/tutorials/basic-feature/protocol/_index.md, content/zh/docs/hertz/tutorials/basic-feature/protocol/_index.md
docs
补充说明基本特性协议部分 index 文档
en:
zh(optional):
=> docs: supplement desc in protocol index.md

content/en/docs/hertz/tutorials/basic-feature/binding-and-validate.md, content/zh/docs/hertz/tutorials/basic-feature/binding-and-validate.md
docs
参数绑定与校验的 tag 部分补充说明
en:
zh(optional):
=> docs: supplement param tag desc

content/en/blog/releases/Kitex/release-v070.md, content/zh/blog/releases/Kitex/release-v070.md
docs
docs: 添加 KiteX v0.7.0 的 realease log
en:
zh(optional):
=> docs: add KiteX v070 release log

content/en/blog/releases/Kitex/release-v070.md
docs
docs: 修改 v0.7.0 KiteX 标题
en:
zh(optional):
=> docs: update release-v070.md to fix title

content/zh/blog/releases/Volo/release-v054.md
=> volo release v0.5.4

content/en/blog/releases/Hertz/release-v050.md, content/zh/blog/releases/Hertz/release-v050.md
docs
en:docs: fix wrong link
zh(optional): 修改错误链接
=> docs: fix wrong link

content/en/docs/hertz/tutorials/example/_index.md, content/zh/docs/hertz/tutorials/example/_index.md
=> docs: fix wrong jwt example link

content/en/docs/hertz/tutorials/basic-feature/middleware/_index.md, content/zh/docs/hertz/tutorials/basic-feature/middleware/_index.md
docs
en: docs: add note part in middleware
zh(optional):  docs: 中间件概览部分增加注意事项
=> docs: add note part in middleware

content/en/docs/volo/volo-grpc/getting-started/part_1.md, content/en/docs/volo/volo-grpc/getting-started/part_3.md, content/en/docs/volo/volo-grpc/getting-started/part_4.md, content/en/docs/volo/volo-thrift/getting-started/part_1.md, content/en/docs/volo/volo-thrift/getting-started/part_3.md, content/en/docs/volo/volo-thrift/getting-started/part_4.md, content/zh/docs/volo/volo-grpc/getting-started/part_1.md, content/zh/docs/volo/volo-grpc/getting-started/part_3.md, content/zh/docs/volo/volo-grpc/getting-started/part_4.md, content/zh/docs/volo/volo-thrift/getting-started/part_1.md, content/zh/docs/volo/volo-thrift/getting-started/part_3.md, content/zh/docs/volo/volo-thrift/getting-started/part_4.md
=> fix: issue #776

content/en/docs/kitex/Tutorials/service-governance/timeout.md, content/zh/docs/kitex/Tutorials/service-governance/timeout.md
=> doc: kitex timeout

content/en/about/_index.html
=> fix: fix the English name of enterprise user

content/en/docs/hertz/tutorials/framework-exten/response_writer.md, content/zh/docs/hertz/tutorials/framework-exten/response_writer.md
=> docs: update extWriter

content/en/docs/_index.md, content/en/docs/cwgo/_index.md, content/en/docs/hertz/_index.md, content/en/docs/kitex/_index.md, content/en/docs/motore/_index.md, content/en/docs/netpoll/_index.md, content/en/docs/pilota/_index.md, content/en/docs/volo/_index.md, content/zh/docs/cwgo/_index.md, content/zh/docs/hertz/_index.md, content/zh/docs/kitex/_index.md, content/zh/docs/motore/_index.md, content/zh/docs/netpoll/_index.md, content/zh/docs/pilota/_index.md, content/zh/docs/volo/_index.md, layouts/docs/list.html
=> chore: add top level description

content/en/docs/hertz/reference/config.md, content/en/docs/hertz/tutorials/basic-feature/engine.md, content/zh/docs/hertz/reference/config.md, content/zh/docs/hertz/tutorials/basic-feature/engine.md
docs
zh(optional): 添加 WithDisableHeaderNamesNormalizing 选项
https://github.com/cloudwego/hertz/issues/957
=> docs: add WithDisableHeaderNamesNormalizing option

content/en/docs/hertz/tutorials/basic-feature/client.md, content/zh/docs/hertz/tutorials/basic-feature/client.md
docs
更新了client.md文档中的表格格式
en: update form's format of client.md. This makes it look more beautiful and convenient for future changes.  
zh(optional): 更新了client.md文档中的表格格式。 这使得它看起来更加美观并且方便之后的更改。
=> docs: update form's format of client.md doc 

content/en/docs/hertz/tutorials/basic-feature/context/request.md, content/zh/docs/hertz/tutorials/basic-feature/context/request.md
docs
en: docs: update clientIp description
zh(optional):  更新 client ip 描述
=> docs: update clientIp description

content/en/docs/kitex/Tutorials/service-governance/fallback.md, content/zh/docs/kitex/Tutorials/service-governance/fallback.md
=> docs: remove unused import

content/en/docs/hertz/tutorials/framework-exten/response_writer.md, content/zh/docs/hertz/tutorials/framework-exten/response_writer.md
docs
en: add ChunkedBodyWriter effect display
zh(optional):
=> docs: add ChunkedBodyWriter effect display

content/en/docs/hertz/tutorials/framework-exten/response_writer.md, content/zh/docs/hertz/tutorials/framework-exten/response_writer.md
docs
en: docs: delete slash
zh(optional):
=> docs: delete slash

content/en/docs/hertz/tutorials/example/_index.md, content/zh/docs/hertz/tutorials/example/_index.md
docs
docs:add example of slog in index.md
在示例代码首页增加 slog 的介绍
=> docs: add example of slog in index.md

.github/workflows/deploy-cn.yml
chore: build use self host machine
en: build use self host machine
zh(optional): 使用自己托管的机器运行 action
=> chore: build use self host machine

README.md
=> Chore: Update README.md for new domain

content/en/docs/kitex/Tutorials/advanced-feature/codec_frugal.md, content/zh/docs/kitex/Tutorials/advanced-feature/codec_frugal.md
=> doc: update framed desc for frugal

content/zh/docs/hertz/tutorials/basic-feature/middleware/requestid.md
=> chore: remove duplicate descriptions

content/en/docs/hertz/tutorials/basic-feature/binding-and-validate.md, content/zh/docs/hertz/tutorials/basic-feature/binding-and-validate.md
en: docs: update binding and validate docs 
zh(optional): 
https://github.com/cloudwego/hertz/issues/413
=> docs: update binding and validate docs 

content/en/docs/kitex/Tutorials/basic-feature/connection_type.md, content/en/docs/kitex/Tutorials/basic-feature/transport_protocol.md, content/zh/docs/kitex/Tutorials/basic-feature/connection_type.md, content/zh/docs/kitex/Tutorials/basic-feature/transport_protocol.md
=> doc: conn type and transport protocols

content/en/docs/kitex/FAQ/_index.md, content/zh/docs/kitex/FAQ/_index.md
en:
zh(optional):  一行命令会被渲染成 mailto 链接
=> chore: fix command rendering error

content/en/blog/releases/Hertz/release-v070.md, content/zh/blog/releases/Hertz/release-v070.md
feat
hertz v0.7.0 release note
en:hertz v0.7.0 release note
zh(optional):
=> feat: hertz v0.7.0

content/en/docs/hertz/tutorials/service-governance/service_discovery/etcd.md, content/zh/docs/hertz/tutorials/service-governance/service_discovery/etcd.md
docs
en: Add documentation for etcd retry
zh(optional): 添加 etcd 重试部分的文档
https://github.com/cloudwego/hertz/issues/974
=> docs: add etcd retry

content/en/security/vulnerability-reporting/_index.html, content/zh/security/vulnerability-reporting/_index.html
=> chore: fix security email link

content/en/docs/volo/overview/_index.md, content/en/docs/volo/volo-grpc/_index.md, content/en/docs/volo/volo-thrift/_index.md, content/zh/docs/volo/_index.md, content/zh/docs/volo/overview/_index.md, content/zh/docs/volo/volo-grpc/_index.md, content/zh/docs/volo/volo-thrift/_index.md
=> chore: add keywords and descriptions for Volo

content/en/docs/cwgo/tutorials/db/_index.md, content/zh/docs/cwgo/tutorials/db/_index.md
en: update cwgo model
zh(optional): 更新 cwgo model 文档
=> chore: update cwgo model

content/en/docs/hertz/tutorials/observability/instrumentation.md, content/zh/docs/hertz/tutorials/observability/instrumentation.md
更新最新版 trace 提示
en:
zh(optional):
=> docs: update trace note for latest release

content/en/docs/hertz/tutorials/basic-feature/context/request.md, content/zh/docs/hertz/tutorials/basic-feature/context/request.md
docs
en:docs: fix setquerystring
zh(optional): 补充说明，setquerystring 后使用 setrequesturi 会覆盖原本想使用的值
=> docs: fix setquerystring

assets/scss/_styles_project.scss, content/zh/_index.html, layouts/_default/baseof.html, layouts/partials/banner.md
=> chore: add banner

content/zh/docs/kitex/Tutorials/advanced-feature/multi_service.md
en: translate Kitex multiple service guide
zh(optional):  翻译 Kitex 支持单 Server 多 Service 文档
=> docs: translate multiple service guide

content/zh/blog/releases/Kitex/release-v080.md
=> docs: release zh doc for Kitex v0.8.0

content/zh/blog/releases/Kitex/release-v080.md
=> docs(kitex): Update release-v080.md

assets/scss/home.scss, content/en/_index.html, content/zh/_index.html
en: logos scroll
zh(optional): logos 滚动
=> feat: logos scroll

content/en/security/vulnerability-reporting/_index.html
New page for Vulnerability Reporting
en:
zh(optional):
=> website: translation for Vulnerability Reporting Page

licenses/LICENSE-bootstrap.txt, licenses/LICENSE-jquery.txt, licenses/LICENSE-popper.txt
en: chore: add licenses
zh(optional): 增加证书
=> chore: add licenses

content/en/cooperation/_index.md, content/zh/cooperation/_index.md
=> chore: update cooperation page & remove blue book

content/en/_index.html, content/zh/_index.html
en:
zh(optional):  中文主页风格与英文主页对齐
=> chore: update zh homepage

content/en/docs/kitex/Tutorials/service-governance/config-center/_index.md, content/en/docs/kitex/Tutorials/service-governance/config-center/zookeeper.md, content/zh/docs/kitex/Tutorials/service-governance/config-center/_index.md, content/zh/docs/kitex/Tutorials/service-governance/config-center/zookeeper.md
=> doc: add the document to introduce the config-zookeeper

content/en/docs/hertz/tutorials/toolkit/annotation.md, content/zh/docs/hertz/tutorials/toolkit/annotation.md
fix
en: 修正 protobuf go_tag 用法
zh(optional): fix the usage for protobuf go_tag
=> fix: protobuf go tag

content/en/docs/hertz/tutorials/basic-feature/engine.md, content/zh/docs/hertz/tutorials/basic-feature/engine.md
fix
en: docs: fix engine.md use function
zh(optional): 
#914
=> docs: fix engine.md use function

content/en/docs/hertz/tutorials/observability/open-telemetry.md, content/zh/docs/hertz/tutorials/observability/open-telemetry.md
en: optimiz the option section in the Hertz OTEL doc
zh(optional): 优化 hertz otel 文档的 option 章节
https://github.com/hertz-contrib/obs-opentelemetry/issues/33
=> feat(otel): optimiz the option section in the Hertz OTEL doc

content/en/docs/kitex/Tutorials/options/client_options.md, content/en/docs/kitex/Tutorials/options/server_options.md, content/zh/docs/kitex/Tutorials/advanced-feature/generic-call/generic-call-reflection.md, content/zh/docs/kitex/Tutorials/options/client_options.md, content/zh/docs/kitex/Tutorials/options/server_options.md
=> fix: link error

content/en/docs/hertz/tutorials/basic-feature/middleware/access-log.md, content/zh/docs/hertz/tutorials/basic-feature/middleware/access-log.md
en:
zh(optional): 更新access log配置，允许用户根据条件是否打印访问日志
=> docs: update access log option

content/en/docs/kitex/Tutorials/code-gen/validator.md
=> docs: optimize validator's english doc

content/en/docs/hertz/tutorials/basic-feature/protocol/sse.md, content/zh/docs/hertz/tutorials/basic-feature/protocol/sse.md
=> docs: hertz sse client

content/en/docs/hertz/tutorials/basic-feature/middleware/i18n.md, content/zh/docs/hertz/tutorials/basic-feature/middleware/i18n.md
docs
en:
zh(optional): 
https://github.com/hertz-contrib/i18n/issues/10
=> docs: update i18n

content/en/docs/hertz/tutorials/service-governance/service_discovery/nacos.md, content/en/docs/kitex/Tutorials/service-governance/service_discovery/nacos.md, content/zh/docs/hertz/tutorials/service-governance/service_discovery/nacos.md, content/zh/docs/kitex/Tutorials/service-governance/service_discovery/nacos.md
docs
en:
zh(optional): 将 nacos/v2 的信息加入到文档中
=> docs: update server_discovery/nacos

content/en/blog/news/bytedance_gonet_practice/index.md, content/en/docs/cwgo/getting-started/_index.md, content/en/docs/hertz/getting-started/_index.md, content/en/docs/kitex/Getting started/_index.md, content/zh/blog/news/bytedance_gonet_practice/index.md, content/zh/docs/cwgo/getting-started/_index.md, content/zh/docs/hertz/getting-started/_index.md, content/zh/docs/kitex/Getting started/_index.md
en:
zh(optional):  修改域名，golang.org 可能不能访问所以也无法跳转
=> chore: change golang.org to go.dev

content/en/docs/volo/volo-grpc/getting-started/_index.md, content/en/docs/volo/volo-thrift/getting-started/_index.md, content/zh/docs/volo/volo-grpc/getting-started/_index.md, content/zh/docs/volo/volo-thrift/getting-started/_index.md
更新 volo 快速开始，移除 nightly 提示。
en:
zh(optional):
=> docs: update volo getting started

content/en/docs/hertz/tutorials/service-governance/service_discovery/redis.md, content/zh/docs/hertz/tutorials/service-governance/service_discovery/redis.md
en: add redis-registry options
zh(optional): 添加 registry redis 扩展的 options
null
=> docs: add redis-registry options

content/en/_index.html, content/zh/_index.html
en:
zh(optional):  更新 cncf 图片，原图暂时失效了
=> chore: update cncf image

content/en/docs/netpoll/Getting started/_index.md, content/zh/docs/netpoll/Getting started/_index.md
docs
优化 nepoll 文档中快速开始部分
en:
zh(optional):
=> docs: optimize quick start doc for netpoll

content/en/docs/kitex/Tutorials/advanced-feature/generic-call/basic_usage.md
Added docs for JSONPbGeneric Basic Usage
en:
zh(optional):
=> feat: Added docs for JSONPbGeneric Basic Usage

content/en/docs/hertz/tutorials/toolkit/more-feature/client.md, content/zh/docs/hertz/tutorials/toolkit/more-feature/client.md
docs
en:
zh(optional): 更新使用 api.post 注解生成 client 侧代码的隐含逻辑
=> docs(hz): update generate client code logic

content/en/about/_index.html, content/zh/about/_index.html
=> chore: update data for about page

content/zh/docs/kitex/Tutorials/code-gen/code_generation.md
=> doc: fix kitex dependency description

content/en/docs/hertz/tutorials/basic-feature/adaptor.md, content/zh/docs/hertz/tutorials/basic-feature/adaptor.md
docs
docs: optimize adaptor.md
=> docs: optimize adaptor.md

content/en/docs/kitex/Tutorials/service-governance/config-center/apollo.md, content/en/docs/kitex/Tutorials/service-governance/config-center/etcd.md, content/en/docs/kitex/Tutorials/service-governance/config-center/file.md, content/en/docs/kitex/Tutorials/service-governance/config-center/nacos.md, content/en/docs/kitex/Tutorials/service-governance/config-center/zookeeper.md, content/en/docs/kitex/Tutorials/service-governance/service_discovery/consul.md, content/en/docs/kitex/Tutorials/service-governance/service_discovery/etcd.md, content/en/docs/kitex/Tutorials/service-governance/service_discovery/eureka.md, content/en/docs/kitex/Tutorials/service-governance/service_discovery/nacos.md, content/en/docs/kitex/Tutorials/service-governance/service_discovery/polaris.md, content/en/docs/kitex/Tutorials/service-governance/service_discovery/rule-based.md, content/en/docs/kitex/Tutorials/service-governance/service_discovery/service-comb.md, content/en/docs/kitex/Tutorials/service-governance/service_discovery/zookeeper.md, content/zh/docs/kitex/Tutorials/service-governance/config-center/apollo.md, content/zh/docs/kitex/Tutorials/service-governance/config-center/etcd.md, content/zh/docs/kitex/Tutorials/service-governance/config-center/file.md, content/zh/docs/kitex/Tutorials/service-governance/config-center/nacos.md, content/zh/docs/kitex/Tutorials/service-governance/config-center/zookeeper.md, content/zh/docs/kitex/Tutorials/service-governance/service_discovery/consul.md, content/zh/docs/kitex/Tutorials/service-governance/service_discovery/etcd.md, content/zh/docs/kitex/Tutorials/service-governance/service_discovery/eureka.md, content/zh/docs/kitex/Tutorials/service-governance/service_discovery/nacos.md, content/zh/docs/kitex/Tutorials/service-governance/service_discovery/polaris.md, content/zh/docs/kitex/Tutorials/service-governance/service_discovery/rule-based.md, content/zh/docs/kitex/Tutorials/service-governance/service_discovery/service-comb.md, content/zh/docs/kitex/Tutorials/service-governance/service_discovery/zookeeper.md
=> docs: add resolver-rule-based doc

content/en/docs/hertz/tutorials/observability/open-telemetry.md, content/zh/docs/hertz/tutorials/observability/open-telemetry.md
增加 hertz opentelemetry tracing WithShouldIgnore 配置文档
en: add docs for hertz obs tracing WithShouldIgnore option
zh(optional): 增加 hertz opentelemetry tracing WithShouldIgnore 配置文档
Fixes https://github.com/hertz-contrib/obs-opentelemetry/issues/34
=> docs: add docs for hertz obs tracing WithShouldIgnore option

content/zh/docs/cwgo/tutorials/client/_index.md
style
- [ x ] This PR title match the format: \<type\>(optional scope): \<description\>
- [ x ] The description of this PR title is user-oriented and clear enough for others to understand.
en:
zh(optional):
=> docs: fix cwgo client  title indent: h2 -> h3

content/zh/docs/kitex/Tutorials/basic-feature/bizstatuserr.md
=> doc: biz status error middleware usage

content/en/docs/kitex/Tutorials/basic-feature/bizstatuserr.md
=> doc: biz status error middleware usage (en)

content/en/blog/releases/Hertz/release-v080.md, content/zh/blog/releases/Hertz/release-v080.md
=> docs(hertz): add release note of v0.8.0

content/en/docs/kitex/Getting started/examples.md, content/zh/docs/kitex/Getting started/examples.md
=> docs: fix the link

content/en/docs/kitex/Tutorials/service-governance/service_discovery/etcd.md, content/zh/docs/kitex/Tutorials/service-governance/service_discovery/etcd.md
=> docs: add etcd instance information doc

content/en/blog/releases/Hertz/release-v050.md, content/en/docs/cwgo/getting-started/_index.md
The commit addresses an incorrect spacing issue in the API query methods in two files: release-v050.md and _index.md. This minor but important fix ensures that the API paths are formatted correctly and improves overall code readability and consistency.
en:
zh(optional):
=> Fix spacing issue in API query methods

layouts/partials/scripts.html, static/js/prism-custom.js
=> feat: add thrift code highlighting

content/en/docs/kitex/Best Practice/error_handle.md, content/en/docs/kitex/Best Practice/graceful_shutdown.md, content/zh/docs/kitex/Best Practice/error_handle.md, content/zh/docs/kitex/Best Practice/graceful_shutdown.md
en: optimize kitex best practice - error handle & graceful shutdown
zh(optional): 优化最佳实践 错误处理 & 优雅停机 文档
=> chore(docs): optimize kitex best practice

content/en/docs/cwgo/tutorials/layout/_index.md, content/en/docs/cwgo/tutorials/templete-extension/_index.md, content/zh/docs/cwgo/tutorials/layout/_index.md, content/zh/docs/cwgo/tutorials/templete-extension/_index.md
docs
en: docs: optimize cwgo layout and custom template document
zh(optional): 优化 cwgo 的 layout 和自定义模板文档
=> docs: optimize cwgo layout and custom template document

content/en/docs/cwgo/tutorials/auto-completion/_index.md, content/zh/docs/cwgo/tutorials/auto-completion/_index.md
docs
en: docs: add auto-completion document
zh(optional):  docs: 增加 cwgo 自动补全文档
=> docs: add auto-completion document

content/en/docs/cwgo/tutorials/cli/_index.md, content/zh/docs/cwgo/tutorials/cli/_index.md
docs
en: doc: optimize cli document
zh(optional): docs: 优化 cwgo cli 文档
=> doc: optimize cli document

content/en/docs/volo/faq/_index.md, content/en/docs/volo/guide/_index.md, content/en/docs/volo/motore/_index.md, content/en/docs/volo/pilota/_index.md, content/zh/docs/volo/faq/_index.md, content/zh/docs/volo/guide/_index.md, content/zh/docs/volo/motore/_index.md, content/zh/docs/volo/pilota/_index.md
en:  add keywords and description
zh(optional):  给 volo 的文档完善 keywords and description
=> docs(volo): add keywords and description

content/zh/docs/kitex/Getting started/tutorial.md
delete the extra words in line482
docs: Documentation only changes.
delete the extra words so that we readers can understand it better.
删除了第482行多余的字
the extra word is in line 482
=> Update tutorial.md , delete the extra words in line 482.

content/en/docs/kitex/Getting started/tutorial.md
Update tutorial.md ,fixed an inconsistency in English Docs
Update tutorial.md ,fixed an inconsistency in English docs, just like the one I just submitted
=> Update tutorial.md ,fixed an inconsistency

content/zh/docs/kitex/Tutorials/advanced-feature/generic-call/basic_usage.md
=> doc(kitex): fix the description for JSONPbGeneric

content/en/docs/kitex/Tutorials/advanced-feature/generic-call/basic_usage.md
=> doc(kitex): fix the description for JSONPbGeneric - EN

content/en/docs/hertz/tutorials/basic-feature/context/response.md, content/zh/blog/news/CloudWeGo_Usability_Construction/index.md, content/zh/docs/hertz/tutorials/basic-feature/context/response.md
fix：Fixed the issue that version 0.123 of hugo would report an error when running this website
en:
zh(optional):
=> Fixed the issue that version 0.123 of hugo would report an error when running this website

content/en/blog/news/Harnessing_the_Power_of_Rust_for_Cloud_Development_with_Volo/index.md, content/zh/docs/volo/volo-thrift/getting-started/_index.md
en:
zh(optional):  不再强调 nightly 版本
=> chore(volo): no longer emphasize the nightly version

content/en/docs/kitex/Best Practice/Integration Testing/_index.md, content/en/docs/kitex/Best Practice/_index.md, content/en/docs/kitex/Best Practice/error_handle.md, content/en/docs/kitex/Best Practice/graceful_shutdown.md, content/en/docs/kitex/Best Practice/usage_attention.md
en: fix typo in kitex best practice
zh(optional):  修复 kitex best practice 英文文档错别字，添加 desciption
=> chore: fix typo in kitex best practice

content/en/docs/kitex/Tutorials/advanced-feature/multi_service.md
docs
en:
Multi-service feature for Kitex thrift and protobuf is now available in the new kitex version v0.9.0.
https://github.com/cloudwego/kitex/pull/1217
zh(optional):
=> docs: update the multi-service doc

content/en/docs/kitex/Tutorials/advanced-feature/multi_service.md
=> docs: add FAQ for kitex multi-service

content/en/docs/kitex/Tutorials/advanced-feature/multi_service.md
=> docs: fix Kitex multi-service doc

content/en/docs/kitex/Tutorials/advanced-feature/multi_service.md
=> docs: update some info about kitex combine service and multi-service

assets/scss/_styles_project.scss
chore: fix banner width in x-large screen
en:  chore: fix banner width in x-large screen
zh(optional): 修复在超大屏幕上的 banner 宽度问题
=> chore: fix banner width in x-large screen

content/zh/docs/kitex/Tutorials/basic-feature/protocol/transport-streaming/thrift_streaming.md
=> docs: fix some inconsistent or typo words used in zh doc `thrift_streaming.md` 

content/zh/docs/kitex/Tutorials/advanced-feature/multi_service.md
=> docs: add FAQ for kitex multi-service(zh)

content/en/docs/kitex/Tutorials/code-gen/combine_service.md, content/zh/docs/kitex/Tutorials/code-gen/combine_service.md
=> docs: update combine_service doc to notify users it is deprecated

content/en/blog/releases/Kitex/release-v090.md, content/zh/blog/releases/Kitex/release-v090.md
=> doc(kitex): add v0.9.0 version introduction

content/en/blog/releases/Netpoll/release-v050.md, content/en/blog/releases/Netpoll/release-v051.md, content/en/blog/releases/Netpoll/release-v060.md, content/zh/blog/releases/Netpoll/release-v050.md, content/zh/blog/releases/Netpoll/release-v051.md, content/zh/blog/releases/Netpoll/release-v060.md
=> docs: add netpoll v0.5~v0.6 releases blog

content/en/docs/kitex/Tutorials/service-governance/config-center/_index.md, content/en/docs/kitex/Tutorials/service-governance/config-center/apollo.md, content/en/docs/kitex/Tutorials/service-governance/config-center/consul.md, content/en/docs/kitex/Tutorials/service-governance/config-center/etcd.md, content/en/docs/kitex/Tutorials/service-governance/config-center/file.md, content/en/docs/kitex/Tutorials/service-governance/config-center/nacos.md, content/en/docs/kitex/Tutorials/service-governance/config-center/zookeeper.md, content/zh/docs/kitex/Tutorials/service-governance/config-center/_index.md, content/zh/docs/kitex/Tutorials/service-governance/config-center/apollo.md, content/zh/docs/kitex/Tutorials/service-governance/config-center/consul.md, content/zh/docs/kitex/Tutorials/service-governance/config-center/etcd.md, content/zh/docs/kitex/Tutorials/service-governance/config-center/file.md, content/zh/docs/kitex/Tutorials/service-governance/config-center/nacos.md, content/zh/docs/kitex/Tutorials/service-governance/config-center/zookeeper.md
=> docs: add config-consul doc

content/en/docs/hertz/tutorials/example/_index.md, content/zh/docs/hertz/tutorials/example/_index.md
=> fix: fix hertz swagger link

content/en/docs/kitex/Tutorials/service-governance/timeout.md, content/zh/docs/kitex/Tutorials/service-governance/timeout.md
=> doc: Server EnableContextTimeout

content/en/docs/kitex/Tutorials/advanced-feature/multi_service.md, content/zh/docs/kitex/Tutorials/advanced-feature/multi_service.md
What type of PR is this?
doc
Check the PR title.
This PR title match the format: (optional scope): .
The description of this PR title is user-oriented and clear enough for others to understand.
Attach the PR updating the user documentation if the current PR requires user awareness at the usage level. [User docs repo](https://github.com/cloudwego/cloudwego.github.io).
(Optional) Translate the PR title into Chinese.
docs: 更新Multiple Services文档的描述
(Optional) More detailed description for this PR(en: English/zh: Chinese).
en:
zh(optional):
(Optional) Which issue(s) this PR fixes:
https://github.com/cloudwego/cloudwego.github.io/issues/1026
=> doc: update description of Multiple Services

content/en/docs/kitex/Getting started/tutorial.md, content/zh/docs/kitex/Getting started/tutorial.md
修复kitex进阶教程中的包引用错误
en:
zh(optional):
=> docs: fix package referencing errors in Kitex's Advanced Tutorial

content/en/docs/kitex/Tutorials/service-governance/loadbalance.md, content/zh/docs/kitex/Tutorials/service-governance/loadbalance.md
增添对 Alias Method 的说明
en:
In Kitex release of [v0.9.0](https://github.com/cloudwego/kitex/releases/tag/v0.9.0) , it added a new loadblancer called `Alias Method`
zh(optional): 
cloudwego/kitex#1184
[cloudwego/kitex#1199](https://github.com/cloudwego/kitex/pull/1199#issuecomment-1987796933)
=> docs(lb): Add description of Alias Method

content/zh/docs/kitex/Overview/_index.md
=> chore: add protocol support in kitex overview

content/en/docs/cwgo/overview/_index.md, content/zh/docs/cwgo/overview/_index.md
docs
en: add cwgo server hex in overview
zh(optional):
=> docs: add cwgo server hex in overview

content/zh/docs/kitex/Getting started/tutorial.md
修正文档主语问题
en:
zh(optional): 
#1046
=> docs: fix the subject

content/zh/docs/kitex/Getting started/examples.md
=> fix(doc): repeated kitex examples

content/en/blog/releases/Volo/release-v0100.md, content/zh/blog/releases/Volo/release-v0100.md
=> docs: add release note for volo 0.10.0

content/en/docs/hertz/tutorials/toolkit/more-feature/template.md, content/zh/docs/hertz/tutorials/toolkit/more-feature/template.md
fix
修复 hz 文档关于模板的错误内容
en: fix hertz template error
zh(optional):
=> fix: hertz template error

content/en/docs/kitex/Tutorials/basic-feature/message_type.md, content/zh/docs/kitex/Tutorials/basic-feature/message_type.md
将message_type.md中的echo.NewServer(handler{})改成echoservice.NewServer(new(handler))
en: Usin "echo.NewServer(handler{})" will report an error
zh(optional):
=> change "echo.NewServer(handler{})" to "echoservice.NewServer(new(handler))" in message_type

content/zh/docs/kitex/Tutorials/service-governance/fallback.md
=> doc(kitex): update fallback.md zh version

content/en/docs/kitex/Tutorials/service-governance/fallback.md
=> doc(kitex): update fallback.md en version

content/en/docs/cwgo/tutorials/client/command.md, content/en/docs/cwgo/tutorials/server/command.md, content/en/docs/cwgo/tutorials/templete-extension/_index.md, content/zh/docs/cwgo/tutorials/client/command.md, content/zh/docs/cwgo/tutorials/server/command.md, content/zh/docs/cwgo/tutorials/templete-extension/_index.md
en: docs: add git template branch desc in cwgo
zh(optional):
=> docs: add git template branch desc in cwgo

content/en/docs/kitex/Best Practice/self_check/panic_self_check.md, content/zh/docs/kitex/Best Practice/self_check/panic_self_check.md
=> docs: fix img path

content/en/docs/kitex/Tutorials/advanced-feature/metainfo.md, content/zh/docs/kitex/Tutorials/advanced-feature/metainfo.md
feat: add receive all the metainfo api
添加client端获取所有metainfo的API
en:
zh(optional): 
最近在开发kitexcall工具的过程中，使用到这个方法，但是发现例子里和官方文档并没有同步展示
=> feat: add receive all the metainfo api

content/zh/blog/news/Kitex_kitexcall_practices/index.md
=> add new blog

.github/workflows/deploy-cn.yml
=> chore: action host X64

content/en/blog/releases/Kitex/release-v0_10_0.md, content/zh/blog/releases/Kitex/release-v0_10_0.md
=> doc: create release-v0_10_0.md

content/en/blog/releases/Kitex/release-v0_10_0.md, content/zh/blog/releases/Kitex/release-v0_10_0.md
=> fix: correct the file path

config.toml, layouts/partials/head.html
en: 
zh(optional): 更新废弃的配置
Fixes #1108
=> chore: update deprecated hugo config

content/en/docs/hertz/tutorials/basic-feature/render.md, content/zh/docs/hertz/tutorials/basic-feature/render.md
=> docs: fix error in render

config.toml, content/zh/_index.html
=> chore: add video link

content/en/docs/kitex/Tutorials/basic-feature/protocol/transport-streaming/thrift_streaming.md
=> docs(kitex): Update thrift_streaming.md to fix code demo

content/zh/docs/kitex/Tutorials/basic-feature/protocol/transport-streaming/thrift_streaming.md
=> docs(kitex): Update thrift_streaming.md(zh) to fix code demo 

content/en/docs/hertz/tutorials/basic-feature/render.md, content/en/docs/hertz/tutorials/service-governance/service_discovery/eureka.md, content/zh/docs/hertz/tutorials/service-governance/service_discovery/eureka.md
=> docs: fix the desc of github.com/hertz-contrib/registry

content/en/docs/kitex/Tutorials/basic-feature/message_type.md, content/zh/docs/kitex/Tutorials/basic-feature/message_type.md
=> docs(kitex): update message type doc

content/en/docs/kitex/Tutorials/advanced-feature/xds.md, content/zh/docs/kitex/Tutorials/advanced-feature/xds.md
en: xds feature introduction
zh(optional):
=> doc(xds): add xds feature document

content/en/docs/kitex/Tutorials/service-governance/retry.md, content/zh/docs/kitex/Tutorials/basic-feature/message_type.md, content/zh/docs/kitex/Tutorials/service-governance/retry.md
=> docs(kitex): retry doc for kitex

content/zh/docs/kitex/Tutorials/advanced-feature/generic-call/basic_usage.md
=> fix: typo in kitex generic-call cn docs

content/en/docs/hertz/tutorials/basic-feature/middleware/cache.md, content/en/docs/hertz/tutorials/basic-feature/middleware/i18n.md, content/en/docs/hertz/tutorials/basic-feature/middleware/recovery.md, content/en/docs/hertz/tutorials/observability/log.md, content/zh/docs/hertz/tutorials/basic-feature/middleware/cache.md, content/zh/docs/hertz/tutorials/basic-feature/middleware/i18n.md, content/zh/docs/hertz/tutorials/basic-feature/middleware/recovery.md, content/zh/docs/hertz/tutorials/basic-feature/proxy.md, content/zh/docs/hertz/tutorials/framework-exten/protocol.md, content/zh/docs/hertz/tutorials/observability/log.md
修改hlog.SystemLogger().CtxErrorf(c, "[Recovery] err=%v\nstack=%s", err, stack)中c为ctx
en:
zh(optional):
=> Update typo in hertz docs

content/zh/blog/releases/Kitex/release-v0_11_0.md
=> doc: update zh release-v0_11_0.md for payload validator doc

content/en/blog/releases/Kitex/release-v0_11_0.md
=> doc: update release-v0_11_0.md for payload validator doc

content/en/docs/kitex/Tutorials/advanced-feature/generic-call/basic_usage.md, content/zh/docs/kitex/Tutorials/advanced-feature/generic-call/basic_usage.md
=> doc: remove basic_usage.md internal words

content/en/docs/hertz/getting-started/_index.md, content/zh/docs/hertz/getting-started/_index.md
en: 
zh(optional): 更新 getting start idl
=> chore: update getting start idl

content/en/docs/kitex/Tutorials/tool/kitexcall.md, content/zh/docs/kitex/Tutorials/tool/kitexcall.md
添加kitexcall工具两个选项：
https://github.com/kitex-contrib/kitexcall/issues/10
https://github.com/kitex-contrib/kitexcall/pull/13
=> doc(kitexcall): add include path for idl & add -e option

content/en/_index.html, content/en/about/_index.html, content/en/docs/hertz/_index.md, content/en/docs/kitex/_index.md, content/zh/_index.html, content/zh/about/_index.html, content/zh/docs/hertz/_index.md, content/zh/docs/kitex/_index.md
=> chore: update project descriptions

.github/workflows/deploy-cn.yml, .github/workflows/push-check.yml
=> chore: update ci

content/en/docs/hertz/tutorials/basic-feature/middleware/gzip.md, content/zh/docs/hertz/tutorials/basic-feature/middleware/gzip.md
=> docs: fix gzip broken link

content/en/docs/kitex/Tutorials/basic-feature/streamx/Kitex+StreamX+-+Stream+Basic+Programming.md, content/en/docs/kitex/Tutorials/basic-feature/streamx/Kitex+StreamX+-+Stream+Error+Handling.md, content/en/docs/kitex/Tutorials/basic-feature/streamx/Kitex+StreamX+-+Stream+FAQ.md, content/en/docs/kitex/Tutorials/basic-feature/streamx/Kitex+StreamX+-+Stream+Metainfo.md, content/en/docs/kitex/Tutorials/basic-feature/streamx/Kitex+StreamX+-+Stream+Middleware.md, content/en/docs/kitex/Tutorials/basic-feature/streamx/_index.md, content/zh/docs/kitex/Tutorials/basic-feature/streamx/Stream+Basic+Programming.md, content/zh/docs/kitex/Tutorials/basic-feature/streamx/Stream+Error+Handling.md, content/zh/docs/kitex/Tutorials/basic-feature/streamx/Stream+FAQ.md, content/zh/docs/kitex/Tutorials/basic-feature/streamx/Stream+Metainfo.md, content/zh/docs/kitex/Tutorials/basic-feature/streamx/Stream+Middleware.md, content/zh/docs/kitex/Tutorials/basic-feature/streamx/_index.md
=> docs: change dir and fix weight

content/en/docs/kitex/Tutorials/code-gen/code_generation.md
=> docs: update code generate english document

content/zh/docs/kitex/Tutorials/code-gen/code_generation.md
=> docs: update code generation document

content/en/docs/kitex/Tutorials/basic-feature/streamx/_index.md, content/zh/docs/kitex/Tutorials/basic-feature/streamx/_index.md
=> docs: add description for streamx

content/en/blog/releases/Kitex/release-v0_12_0.md, content/zh/blog/releases/Kitex/release-v0_12_0.md
=> docs: release Kitex v0.12.0

content/zh/docs/eino/quick_start/agent_llm_with_tools.md
=> fix: quick start code

content/zh/docs/kitex/Best Practice/Integration Testing/mock_client.md
docs: add Windows environment example for generating Kitex mock client
=> docs: add Windows environment example for generating Kitex mock client

content/zh/docs/eino/core_modules/chain_and_graph_orchestration/call_option_capabilities.md, content/zh/docs/eino/core_modules/chain_and_graph_orchestration/callback_manual.md, content/zh/docs/eino/core_modules/chain_and_graph_orchestration/orchestration_design_principles.md, content/zh/docs/eino/core_modules/chain_and_graph_orchestration/stream_programming_essentials.md, content/zh/docs/eino/core_modules/devops/ide_plugin_guide.md, content/zh/docs/eino/core_modules/devops/visual_debug_plugin_guide.md, content/zh/docs/eino/core_modules/devops/visual_orchestration_plugin_guide.md, content/zh/docs/eino/core_modules/flow_integration_components/react_agent_manual.md, content/zh/docs/eino/ecosystem_integration/callbacks/callback_langfuse.md, content/zh/docs/eino/overview/_index.md, content/zh/docs/eino/overview/eino_open_source.md
=> docs: eino image resize

content/en/docs/hertz/tutorials/basic-feature/json.md, content/zh/docs/hertz/tutorials/basic-feature/json.md
update sonic features
en:
zh(optional):
=> doc: Update json.md

content/zh/docs/eino/quick_start/agent_llm_with_tools.md
fix: fix package refrence error
=> fix package refrence error

content/en/docs/hertz/tutorials/basic-feature/graceful-shutdown.md, content/zh/docs/hertz/tutorials/basic-feature/graceful-shutdown.md
=> fix: fix hertz graceful shutdown

config.toml, content/en/docs/hertz/tutorials/third-party/middleware/csrf.md, content/en/docs/kitex/FAQ/_index.md, content/zh/community/meeting_notes/2022-06-02/_index.md, content/zh/community/meeting_notes/2022-11-03/_index.md, content/zh/docs/hertz/tutorials/third-party/middleware/csrf.md, content/zh/docs/kitex/FAQ/_index.md, layouts/_default/content.html, layouts/community/list.html, layouts/docs/list.html, layouts/partials/disqus-comment.html, layouts/partials/google_analytics.html, layouts/partials/head-css.html, layouts/partials/scripts.html, layouts/security/list.html, layouts/swagger/list.html, vercel.json
=> chore: fix hugo deprecated syntax

.github/workflows/deploy-cn.yml
=> ci: update hugo version

.github/workflows/deploy-cn.yml
=> ci: remove deprecated --verbose option

content/zh/docs/eino/core_modules/devops/ide_plugin_guide.md
=> doc: add plugin requirements version

.github/workflows/gh-page.yml
=> feat: deploy to github page

config.toml, content/en/docs/hertz/tutorials/third-party/open-telemetry.md, content/zh/docs/hertz/tutorials/third-party/open-telemetry.md
en: add business solution tab with external link（zh only）
zh(optional):  添加企业级解决方案和外链（仅限中文页面）
=> chore(zh): add new tab with external link

content/zh/docs/eino/core_modules/devops/ide_plugin_guide.md
docs: update idea plugin guide
=> doc: update idea plugin guide

layouts/partials/handle-version-switch-404.html, static/js/outbound-link.js
=> chore: fix some js warning

content/zh/docs/eino/core_modules/devops/ide_plugin_guide.md
docs: update eino install guide title to h2
=> doc(Eino): update eino install guide title to h2

content/en/_index.html, content/en/about/_index.html, content/zh/_index.html, content/zh/about/_index.html
en: update project info for homepage and about page 
zh(optional):
=> chore: update homepage and about page

content/en/docs/eino/core_modules/flow_integration_components/react_agent_manual.md, content/en/docs/eino/ecosystem/chat_model/chat_model_ark.md, content/en/docs/eino/ecosystem/chat_model/chat_model_ollama.md, content/en/docs/eino/ecosystem/chat_model/chat_model_openai.md, content/en/docs/eino/ecosystem/tool/tool_duckduckgo_search.md, content/en/docs/eino/ecosystem/tool/tool_googlesearch.md, content/zh/docs/eino/core_modules/flow_integration_components/react_agent_manual.md, content/zh/docs/eino/ecosystem_integration/chat_model/chat_model_ark.md, content/zh/docs/eino/ecosystem_integration/chat_model/chat_model_ollama.md, content/zh/docs/eino/ecosystem_integration/chat_model/chat_model_openai.md, content/zh/docs/eino/ecosystem_integration/tool/tool_duckduckgo_search.md, content/zh/docs/eino/ecosystem_integration/tool/tool_googlesearch.md
docs: update eino google search examples
=> docs: update eino googlesearch

assets/scss/about.scss
=> chore: fix about mobile style

content/zh/docs/eino/core_modules/flow_integration_components/react_agent_manual.md
update documentation about eino's react agent: 
1. Update default StreamToolCallChecker function
2. specify the pitfalls of default StreamToolCallChecker
=> feat: update StreamToolCallChecker

content/en/docs/eino/core_modules/chain_and_graph_orchestration/chain_graph_introduction.md, content/zh/docs/eino/core_modules/chain_and_graph_orchestration/chain_graph_introduction.md
=> docs: eino graph update

content/en/docs/hertz/tutorials/third-party/middleware/sentry.md, content/zh/docs/hertz/tutorials/third-party/middleware/sentry.md
=> fix(hertz): wrong function signature

content/en/docs/eino/core_modules/flow_integration_components/react_agent_manual.md, content/zh/docs/eino/core_modules/flow_integration_components/react_agent_manual.md
feat: adjust StreamToolCallChecker documentation
=> feat: adjust StreamToolCallChecker documentation

content/en/docs/hertz/tutorials/basic-feature/context/_index.md, content/zh/docs/hertz/tutorials/basic-feature/context/_index.md
docs
en: clearly concurrency safety description
zh(optional):
=> docs(hertz): optimized context docs for concurrency safety

content/en/docs/eino/core_modules/flow_integration_components/react_agent_manual.md, content/zh/docs/eino/core_modules/flow_integration_components/react_agent_manual.md
Update the api to the latest version
=> docs(Eino):Comply with new version of api

content/zh/docs/kitex/Getting started/tutorial.md
=> docs: fix typo in tutorial.md

content/en/docs/eino/core_modules/components/document_loader_guide/_index.md, content/en/docs/eino/core_modules/components/document_loader_guide/document_parser_interface_guide.md, content/en/docs/eino/core_modules/components/document_transformer_guide.md, content/en/docs/eino/core_modules/components/embedding_guide.md, content/en/docs/eino/core_modules/components/indexer_guide.md, content/en/docs/eino/core_modules/components/retriever_guide.md, content/en/docs/eino/core_modules/components/tools_node_guide/_index.md, content/en/docs/eino/core_modules/components/tools_node_guide/how_to_create_a_tool.md, content/en/docs/eino/ecosystem_integration/_index.md, content/en/docs/eino/ecosystem_integration/chat_model/chat_model_ark.md, content/en/docs/eino/ecosystem_integration/chat_model/chat_model_ollama.md, content/en/docs/eino/ecosystem_integration/chat_model/chat_model_openai.md, content/en/docs/eino/ecosystem_integration/chat_template/chat_template_mcp.md, content/en/docs/eino/ecosystem_integration/document/parser_html.md, content/en/docs/eino/ecosystem_integration/document/parser_pdf.md, content/en/docs/eino/ecosystem_integration/document/splitter_markdown.md, content/en/docs/eino/ecosystem_integration/document/splitter_recursive.md, content/en/docs/eino/ecosystem_integration/document/splitter_semantic.md, content/en/docs/eino/ecosystem_integration/embedding/embedding_ark.md, content/en/docs/eino/ecosystem_integration/embedding/embedding_openai.md, content/en/docs/eino/ecosystem_integration/indexer/_index.md, content/en/docs/eino/ecosystem_integration/tool/tool_duckduckgo_search.md, content/en/docs/eino/ecosystem_integration/tool/tool_googlesearch.md, content/en/docs/eino/ecosystem_integration/tool/tool_mcp.md, content/en/docs/eino/quick_start/simple_llm_application.md, content/zh/docs/eino/core_modules/components/document_transformer_guide.md
docs: update document transformer
=> docs: update document transformer

content/en/docs/eino/core_modules/chain_and_graph_orchestration/orchestration_design_principles.md, content/zh/docs/eino/core_modules/chain_and_graph_orchestration/orchestration_design_principles.md
=> feat: update merge register & with eager execution

content/en/docs/eino/quick_start/_index.md, content/en/docs/hertz/getting-started/_index.md, content/en/docs/kitex/Getting started/_index.md, content/zh/docs/eino/quick_start/_index.md, content/zh/docs/hertz/getting-started/_index.md, content/zh/docs/kitex/Getting started/_index.md
=> chore: update getting-started docs

content/en/docs/eino/core_modules/flow_integration_components/multi_agent_hosting.md, content/zh/docs/eino/core_modules/flow_integration_components/multi_agent_hosting.md
update Eino's host multi-agent documentation with:
1. StreamToolCallChecker
2. multiple intents
=> feat: update host multi-agent docs

content/en/docs/eino/ecosystem_integration/document/loader_local_file.md, content/zh/docs/eino/ecosystem_integration/document/loader_local_file.md
=> fix: document local file parser import path

content/en/docs/kitex/Tutorials/advanced-feature/generic-call/basic_usage.md, content/zh/docs/kitex/Tutorials/advanced-feature/generic-call/basic_usage.md
=> docs(kitex): fix generic example typo

content/en/blog/releases/Kitex/release-v0_14_0.md, content/en/docs/hertz/tutorials/basic-feature/sse.md, content/zh/blog/releases/Kitex/release-v0_14_0.md, content/zh/docs/hertz/tutorials/basic-feature/sse.md
=> docs: kitex v0.14.0 release blog

content/en/docs/cwgo/overview/_index.md, content/en/docs/hertz/tutorials/example/_index.md, content/zh/docs/cwgo/getting-started/_index.md, content/zh/docs/hertz/tutorials/example/_index.md
=> chore: update cwgo doc and hertz examples

content/en/docs/eino/core_modules/components/document_loader_guide/_index.md, content/zh/docs/eino/core_modules/components/document_loader_guide/_index.md
=> fix(doc_loader): correct chain input type

content/en/docs/eino/ecosystem_integration/embedding/embedding_ollama.md, content/zh/docs/eino/ecosystem_integration/embedding/embedding_ollama.md
=> docs(Eino): add doc for ollama embedding

content/en/docs/eino/ecosystem_integration/tool/tool_bingsearch.md, content/en/docs/eino/quick_start/_index.md, content/en/docs/eino/quick_start/simple_llm_application.md, content/zh/docs/eino/ecosystem_integration/retriever/retriever_milvus.md, content/zh/docs/eino/ecosystem_integration/tool/tool_bingsearch.md
=> chore: fix broken link in Eino doc

content/en/docs/eino/core_modules/components/embedding_guide.md, content/zh/docs/eino/core_modules/components/embedding_guide.md
=> doc(eino): correct embedding example

layouts/partials/page-meta-links.html
=> fix: sidebar meta links error

content/zh/docs/eino/core_modules/eino_adk/outline.md
更新 ADK 概述中关于 Loop Agent 的部分
en:
zh(optional):
=> docs(eino): update loop agent section in adk outline

content/zh/docs/eino/core_modules/components/tools_node_guide/_index.md
docs: update doc about toolsNode
1. fix typo,  tool.Tool -> tool.BaseTool
2. change compose.NewToolsNode to compose.NewToolNode, since compose.NewToolsNode is not exist
3. add example code about ToolsNodeOption
en:
zh(optional):
=> docs(Eino): update doc about toolsNode

content/en/docs/eino/core_modules/components/document_loader_guide/_index.md, content/zh/docs/eino/core_modules/components/document_loader_guide/_index.md
=> fix(doc_eino): loader interface path

content/en/docs/hertz/tutorials/basic-feature/hooks.md, content/zh/docs/hertz/tutorials/basic-feature/hooks.md
```go
// In netpoll library, OnAccept is called after connection accepted
// but before adding it to epoll. OnConnect is called after adding it to epoll.
// The difference is that onConnect can get data but OnAccept cannot.
// If you'd like to check whether the peer IP is in the blacklist, you can use OnAccept.
// In go net, OnAccept is executed after connection accepted but before establishing
// tls connection. OnConnect is executed after establishing tls connection.
OnAccept  func(conn net.Conn) context.Context
OnConnect func(ctx context.Context, conn network.Conn) context.Context
```
Update docs according to the above code.
=> docs(hertz): update doc about hertz hooks

.github/workflows/deploy-cn.yml
=> ci: sync deleted files

.github/workflows/deploy-cn.yml
=> ci: Force overwrite when syncing to OSS

content/en/blog/releases/Kitex/release-v0_15_1.md, content/zh/blog/releases/Kitex/release-v0_15_1.md
=> docs: add description of breaking changes of kitex v0.15.1
