content/en/docs/Getting started/_index.md
content/zh/docs/Getting started/_index.md

Fixes #50 快速安装页面的go get修改为go install避免出现系统提示
```
go get: installing executables with 'go get' in module mode is deprecated.
Use 'go install pkg@version' instead.
For more information, see https://golang.org/doc/go-get-install-deprecation
or run 'go help get' or 'go help install'.
```

快速安装页面的go get修改为go install

---

package-lock.json

fixed: https://github.com/cloudwego/cloudwego.github.io/security/dependabot/package-lock.json/ansi-regex/open

chore: update dependency

---

layouts/404.html

`{{.Site.Language.Lang}}` is fixed by template, match language-key from location instead

fix(404): match language from location dynamically

---

content/en/docs/kitex/Getting started/_index.md
content/en/docs/kitex/Reference/exception.md
content/en/docs/kitex/Tutorials/advanced-feature/generic_call.md
content/en/docs/kitex/Tutorials/advanced-feature/metainfo.md
content/en/docs/kitex/Tutorials/basic-feature/logging.md
content/en/docs/kitex/Tutorials/framework-exten/registry.md

Hi, recently I walked through the official docs of Kitex and found some typos. This PR fixed all of them.

fix: en docs typo fix for kitex

---

content/en/docs/hertz/overview/_index.md

Hi there,
I am an early adapter of Hertz back in 2021, it  is so great it has made its way to the open source community. I came across the overview of Hertz and found some improvement could be done on its English translation. It is my best effort to make it fluent to read while preserving the original meaning.

docs: translate /docs/hertz/overview/_index.md

---

content/en/docs/kitex/Tutorials/basic-feature/transport_protocol.md
content/zh/docs/kitex/Tutorials/basic-feature/transport_protocol.md

docs: translate basic-feature/transport_protocol chapter of Kitex from Chinese to English.
en: Provides the documentation of transport protocols in English.
zh: 补充传输协议说明文档
relevant issue: [Kitex 568](https://github.com/cloudwego/kitex/issues/568)

docs: translate basic-feature/transport_protocol/

---

content/en/docs/hertz/tutorials/service-governance/service_discovery.md

en: The service_discovery English docs for the Hertz Tutorials was added.
zh: 补充了 Hertz Tutorials 中服务发现部分的英文文档。
Fixes [(#199)](https://github.com/cloudwego/hertz/issues/199)

[docs]: translate hertz tutorials/tutorials/service-governance/service_discovery/ (#199)

---

content/en/docs/kitex/Overview/_index.md

docs: Documentation fix
en:  kitex-example's link is 404 right now
no issue related

[fix] update kitex-example link in kitex overview

---

content/en/docs/kitex/Tutorials/framework-exten/registry.md
content/zh/docs/kitex/Tutorials/framework-exten/registry.md

docs: corrected kitex registry example symbols
en: docs: corrected kitex registry example symbols 
zh: 修正kitex服务注册示例的代码单引号为双引号

docs: corrected kitex registry example symbols

---

content/zh/docs/motore/faq/q1_gat.md

在 [使用 GAT，解决了什么问题？](https://www.cloudwego.io/zh/docs/motore/faq/q1_gat/) 的最后一节中，有段话描述如下：    
```
那么我们该怎么约束的 Future 的 lifetime 为 'cx 呢
```
其中**怎么约束的 Future 的 lifetime**部分缺少修饰词，结合上下文，应添加改为：
```
那么我们该怎么约束返回的 Future 的 lifetime 为 'cx 呢
```
en: 
zh:

docs(q1_gat.md):补充文档最后章节缺漏的修饰词

---

content/en/docs/hertz/tutorials/basic-feature/route.md
content/zh/docs/hertz/tutorials/basic-feature/route.md

doc
en: improve route doc
zh: 改善路由文档中文部分

docs: improve route doc

---

content/en/docs/hertz/tutorials/basic-feature/middleware/cors.md
content/zh/docs/hertz/tutorials/basic-feature/middleware/cors.md

docs
en: improve hertz-cors docs
zh: 完善 hertz-cors 的文档

docs: improve hertz-cors docs

---

content/en/docs/hertz/tutorials/basic-feature/middleware/requestid.md
content/zh/docs/hertz/tutorials/basic-feature/middleware/requestid.md

docs
en: add docs for Request ID middleware
zh: 添加Request ID中间件的文档

doc: add docs for request id middleware

---

content/en/docs/hertz/tutorials/basic-feature/unit-test.md
content/zh/docs/hertz/tutorials/basic-feature/unit-test.md

docs: add another example for UT, to make it more simply.
en: This dock PR comes from Hertz Framework PR https://github.com/cloudwego/hertz/pull/333. Add more examples for new users to write their unit tests more efficiently and more simple. Which is useful for the project created by `hertz new` template.
zh: 来自于 Hertz框架的PR This dock PR comes from Hertz Framework PR https://github.com/cloudwego/hertz/pull/333。 增加更贴近实际使用场景的单测样例，让新手可以更快开发。在使用了`hertz new`命令创建的示例模板中使用更快捷。

docs: add another example for ut

---

content/en/docs/hertz/reference/config.md
content/en/docs/hertz/tutorials/basic-feature/retry.md
content/zh/docs/hertz/reference/config.md
content/zh/docs/hertz/tutorials/basic-feature/retry.md

docs 
en: Add version information for hertz retry. Optimize the English document because there was a sentence in the wrong place before
zh: 增加 hertz retry 的版本信息，优化英文文档，以前有句话位置有误

docs: add version information for hertz retry

---

content/en/docs/hertz/tutorials/basic-feature/route.md
content/zh/docs/hertz/tutorials/basic-feature/route.md

docs
en:  Fix an error in the routing document, httpMethod in h.Handle() must be all capitalized
zh:  修改了路由文档中的一处错误，  h.Handle()  方法下的 httpMethod 参数必须全为大写

docs: Fix an error in the routing document

---

content/zh/docs/hertz/tutorials/basic-feature/middleware/cors.md

docs: fix typo in hertz middleware cors

---

content/en/docs/hertz/tutorials/toolkit/template.md
content/zh/docs/hertz/tutorials/toolkit/template.md

docs
en: add file type tags for better display of documents
zh: 添加文件类型标签使文档得到更好的显示效果
Before: 
Now:

docs: add file type tags for better display of docs

---

layouts/partials/sidebar-tree.html

chore: top level navbar missing in latest hugo
en: top level navbar missing in latest hugo
zh: 左侧导航栏在最新版本hugo消失不见了。
Fixes #459

chore: top level navbar missing in latest hugo

---

content/en/docs/hertz/tutorials/basic-feature/middleware/etag.md
content/zh/docs/hertz/tutorials/basic-feature/middleware/etag.md

docs
en: Added `etag` middleware documentation
zh: 新增 `etag` 中间件的文档
https://github.com/cloudwego/hertz/issues/592

docs: add Etag middleware

---

content/zh/docs/kitex/Getting started/_index.md

Add more details on the compatibility issue regarding thrift version 0.13
optimize
en: add common error message when thrift >=0.14 is used and why we need to use 0.13
zh:

optimize: details on compatibility with thrift

---

content/zh/docs/kitex/Getting started/_index.md

settings.py is for ByteDance's internal deployment.
fix: A bug fix
en: settings.py is not generated by the open source version of kitex tool.
zh:

fix: settings.py is not generated automatically

---

content/en/docs/hertz/tutorials/basic-feature/binding-and-validate.md
content/zh/docs/hertz/tutorials/basic-feature/binding-and-validate.md

This commit adds documentation for required parameter in [Binding and validate](https://www.cloudwego.io/docs/hertz/tutorials/basic-feature/binding-and-validate).
Required paramter is a important binding feature but it's missing in documentation.
en: add documentation for required parameter
zh: 补充必填参数文档

doc: add documentation for required parameter

---

content/en/docs/hertz/getting-started/_index.md
content/zh/docs/hertz/getting-started/_index.md

fix
添加 go mod init 命令
目前 hz new 在不使用 -mod 的情况下不会生成 go.mod，quick-start 需要修复

fix: add go mod init

---

content/en/docs/hertz/tutorials/basic-feature/json.md
content/zh/docs/hertz/tutorials/basic-feature/json.md

docs
将json_marshal文档移到基本特性中
en:docs: move json_marshal to basic_feature
zh(optional): 将json_marshal文档移到基本特性中

docs: move json_marshal to basic_feature

---

content/en/docs/hertz/tutorials/example/_index.md
content/zh/docs/hertz/tutorials/example/_index.md

docs
en:docs: add more example
zh(optional): 添加更多的代码示例链接

docs: add more example

---

content/zh/docs/hertz/tutorials/basic-feature/binding-and-validate.md

feat
hertz 绑定重构文档
en: hertz binding refactor doc
zh(optional):  hertz 绑定重构文档

feat: hertz binding refactor

---

content/zh/docs/hertz/tutorials/basic-feature/binding-and-validate.md

optimize
优化 hertz 参数绑定文档
en: optimize hertz binding doc
zh(optional): 优化 hertz 参数绑定文档

optimize(hertz): hertz binding doc

---

layouts/partials/hooks/body-end.html

en: 
zh(optional): 更换搜索结果的域名，允许cn域名搜索

chore: change search result domain

---

content/en/docs/hertz/tutorials/basic-feature/middleware/cache.md
content/zh/docs/hertz/tutorials/basic-feature/middleware/cache.md

docs
优化Cache文档可配置项展示
####(Optional) More detailed description for this PR(en: English/zh: Chinese).
en:According to the current document content, the configurable item display method has been optimized
zh(optional):根据当前文档内容优化了可配置项展示方式
Fixes #649

docs: optimize cache doc configuration show 

---

content/en/blog/releases/Kitex/release-v070.md

chore: fix KiteX -> Kitex

---

content/en/docs/kitex/Tutorials/service-governance/config-center/nacos.md
content/zh/docs/kitex/Tutorials/service-governance/config-center/nacos.md

doc: add the document to introduce the config-nacos

---

content/en/docs/hertz/tutorials/basic-feature/context/response.md
content/zh/docs/hertz/tutorials/basic-feature/context/response.md

docs
docs: 修复 SetCookie 函数签名
en:
zh(optional): 
This PR fixs SetCookie function signature to match current version (v0.8.0). I will open a new PR when https://github.com/cloudwego/hertz/pull/1048 has been merged into develope.

docs: fix SetCookie function signature

---

content/en/docs/kitex/Tutorials/basic-feature/message_type.md
content/zh/docs/kitex/Tutorials/basic-feature/message_type.md

添加k-consts.go到用kitex工具生成的代码目录中
en: The added content is in docs/kitex/Tutorials/basic-feature/message_type
zh(optional):

fix: Add "k-consts.go" item in the layout of generated code in docs/kitex

---

content/zh/docs/kitex/Getting started/tutorial.md

Fixed an inconsistency between service name in stock idl and service name in later documentation
There is an inconsistency between service name in stock idl, which is 'GetItemStock' and service name in later documentation, which is stockservice
在前面的stock的idl定义中，service name被定义成了GetItemStock，而在后面的文档中一直使用的是stockservice，前后不一致导致按照文档运行库存服务的时候会出现 找不到stockservice 的import错误
在前面的stock的idl定义中，service name被定义成了GetItemStock，而在后面的文档中一直使用的是stockservice，前后不一致导致按照文档运行库存服务的时候会出现 找不到stockservice 的import错误，经过我的测试，把最开始的stock idl定义中的service name 改成stockservice与后面保持一致就可以运行成功。请您详细看一下我提的问题，更改之前也请您自己检查一下，我还是小白，不能保证我的理解就是对的。不过我觉得这个问题还是挺严重的。如果不更改的话，一路照着文档做都会报错，让人很摸不着头脑。

Update tutorial.md ,fixed an inconsistency

---

content/en/docs/cwgo/getting-started/_index.md
content/en/docs/cwgo/tutorials/client/command.md
content/en/docs/cwgo/tutorials/client/example_pb.md
content/en/docs/cwgo/tutorials/client/example_thrift.md
content/en/docs/cwgo/tutorials/server/command.md
content/en/docs/cwgo/tutorials/server/example_pb.md
content/en/docs/cwgo/tutorials/server/example_thrift.md
content/zh/docs/cwgo/getting-started/_index.md
content/zh/docs/cwgo/tutorials/client/command.md
content/zh/docs/cwgo/tutorials/client/example_pb.md
content/zh/docs/cwgo/tutorials/client/example_thrift.md
content/zh/docs/cwgo/tutorials/server/command.md
content/zh/docs/cwgo/tutorials/server/example_pb.md
content/zh/docs/cwgo/tutorials/server/example_thrift.md

fix
en: Change the parameter service to server_name.The service parameter name is not easily understood by the user.
zh: 修复service参数名称为server_name,service参数名称不容易被用户理解。

fix:change the parameter service to server_name

---

content/en/blog/releases/Kitex/release-v0_11_0.md
content/zh/blog/releases/Kitex/release-v0_11_0.md

doc: optmize release log for kitex v0.11.0

---

content/zh/docs/kitex/Reference/transport_protocol_ttheader.md

add info ids describe
增加协议部分 关于 info ids 的描述信息 
en: add some info for info ids part
zh(optional): 增加协议部分 关于 info ids 的描述信息

<docs>: update protocol describe info

---

content/zh/docs/eino/core_modules/chain_and_graph_orchestration/stream_programming_essentials.md
content/zh/docs/eino/core_modules/flow_integration_components/react_agent_manual.md
content/zh/docs/eino/overview/_index.md
content/zh/docs/eino/quick_start/complex_business_logic_orchestration.md
content/zh/docs/eino/quick_start/simple_llm_application.md

feat: update quick start doc

---

content/zh/docs/eino/core_modules/components/lambda_guide.md

Modify the type definition of the lambda example in lambda_guide.md. 
The original code wrongly declared that both the input and output could be any custom types.
The correct definition is based on the code implementation in eino, specifically in the file [types_lambda.go](https://github.com/cloudwego/eino/blob/main/compose/types_lambda.go) around lines 110 - 140.

docs: update eino doc lambda_guide.md

---

content/en/docs/hertz/tutorials/third-party/open-telemetry.md
content/en/docs/kitex/Tutorials/third-party/observability.md
content/zh/docs/hertz/tutorials/third-party/open-telemetry.md
content/zh/docs/kitex/Tutorials/third-party/observability.md

refine document for opentelemetry-compile-time-instrumentation
1. [open-telemetry official project link](https://github.com/open-telemetry/opentelemetry-go-compile-instrumentation)
2. [open-telemetry official technical blog](https://opentelemetry.io/blog/2025/go-compile-time-instrumentation)
3. [alibaba compile-time instrumentation](https://github.com/alibaba/opentelemetry-go-auto-instrumentation)
4. [datadog compile-time instrumentation implementation](https://github.com/datadog/orchestrion)

refine document for opentelemetry-compile-time-instrumentation

---

content/en/docs/hertz/tutorials/basic-feature/graceful-shutdown.md
content/zh/docs/hertz/tutorials/basic-feature/graceful-shutdown.md

en:
zh(optional): 更新优雅退出
Fixes https://github.com/cloudwego/hertz/issues/1330

docs: update hertz graceful shutdown

---

content/en/docs/eino/core_modules/components/chat_template_guide.md
content/en/docs/eino/core_modules/components/document_loader_guide/document_parser_interface_guide.md
content/en/docs/eino/ecosystem/chat_template/chat_template_mcp.md
content/zh/docs/eino/core_modules/components/chat_template_guide.md
content/zh/docs/eino/core_modules/components/document_loader_guide/document_parser_interface_guide.md
content/zh/docs/eino/ecosystem_integration/chat_template/chat_template_mcp.md
content/zh/docs/eino/overview/_index.md

docs: eino update prompt

---

content/en/docs/eino/ecosystem/callbacks/callback_langfuse.md
content/zh/docs/eino/ecosystem_integration/callbacks/callback_langfuse.md

修复 langfuse 集成中示例代码的错误。
en:
None.
zh(optional): 
无。
None.

docs(Eino): fix example code of langfuse callback

---

content/en/docs/eino/ecosystem/tool/tool_mcp.md
content/zh/docs/eino/ecosystem_integration/tool/tool_mcp.md

Uniform variable names, changing tools to mcpTools to avoid misunderstandings

docs(Eino):Uniform context variable naming

---

content/en/docs/eino/ecosystem_integration/indexer/indexer_milvus.md
content/zh/docs/eino/ecosystem_integration/indexer/indexer_milvus.md

closed #1330 
如果要使用milvus的indexer，指定collection的时候，如果要使用自己创建的collection，必须指定Fields，否则会报错，无法正常使用，详情见https://github.com/cloudwego/eino-ext/issues/252
原文档缺乏这部分信息补充，导致自己排查了很久才发现相应问题，这个pr补充了相应信息

修复milvus的indexer文档，缺乏”document配置必须搭配fields配置“这一信息，导致容易误用问题

---

content/en/blog/releases/Hertz/release-v0_10_0.md
content/en/docs/hertz/tutorials/basic-feature/_index.md
content/en/docs/hertz/tutorials/basic-feature/http-adaptor.md
content/en/docs/hertz/tutorials/basic-feature/sse.md
content/zh/blog/releases/Hertz/release-v0_10_0.md
content/zh/docs/hertz/tutorials/basic-feature/_index.md
content/zh/docs/hertz/tutorials/basic-feature/http-adaptor.md
content/zh/docs/hertz/tutorials/basic-feature/sse.md

docs: add doc for hertz v0.10.0

---

content/en/docs/hertz/tutorials/observability/log.md
content/zh/docs/hertz/tutorials/observability/log.md

解决Herz 中英文文档中可观测性质-日志模块的,示例代码问题
latency := end.Sub(start).Microseconds 修正为
latency := end.Sub(start).Microseconds()

docs(hertz)：解决日志示例代码的错误

---

content/en/docs/hertz/tutorials/third-party/protocol/_index.md
content/zh/docs/hertz/tutorials/third-party/protocol/_index.md

当前对于协议的三方扩展的索引页面不再需要 SSE 的相关内容

docs(hz): Remove SSE from tutorials/third-party/_index.md and Synchronize keywords

---

content/zh/docs/hertz/getting-started/_index.md

en: `hz new -idl hello.thrift` indicates that the `hello.thrift` file is in the current directory, while the example code `idl\hello.thrift` shows that it's in `.\idl`. It's confusing!
zh(optional):  `hz new -idl hello.thrift` 表明 `hello.thrift` 在当前目录，但下面的代码示例中又有注释 `// idl/hello.thrift`，看起来很矛盾，所以改了代码注释。

docs(hertz): fix misleading file path in quick start tutorial

---

content/en/blog/releases/Kitex/release-v0_15_1.md
content/en/docs/kitex/Tutorials/basic-feature/streamx/StreamX_Error_Handling.md
content/en/docs/kitex/Tutorials/basic-feature/streamx/StreamX_Lifecycle_Control.md
content/en/docs/kitex/Tutorials/code-gen/idl_enumeration_type.md
content/zh/blog/releases/Kitex/release-v0_15_1.md
content/zh/docs/kitex/Tutorials/basic-feature/streamx/StreamX_Error_Handling.md
content/zh/docs/kitex/Tutorials/basic-feature/streamx/StreamX_Lifecycle_Control.md
content/zh/docs/kitex/Tutorials/code-gen/idl_enumeration_type.md

feat: release kitex v0.15.1
